import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { KeyRound, LogOut, Wifi, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import synthesyxLogo from "@/assets/synthesyx-logo.svg";
import {
  CHROMATOGRAM_Y_FLOOR_MAU,
  TraceChart,
  colorForStream,
  type RunMarker,
  type TraceSeries,
} from "@/components/live-instruments/trace-chart";
import { LiveWindowControls, useLiveWindow } from "@/components/live-instruments/live-window";
import { LIVE_HISTORY_MINUTES } from "@/components/live-instruments/use-instrument-live-feed";
import { usePublicLiveFeed } from "@/components/public-live/use-public-live-feed";

/**
 * Public live chromatogram viewer. No Supabase login: a one-time passcode
 * (generated by an admin on the Live Instruments page) is redeemed once into
 * a session token for the invite's window (start + length chosen by the
 * admin), kept in this browser; the page then polls
 * /api/public/live/snapshot, which serves detector signals only. The viewer
 * sees the sample name and the chromatogram, can pan the window, and nothing
 * else — there is no route a viewer token can change anything through.
 */
export const Route = createFileRoute("/live")({ component: PublicLivePage });

const STORAGE_KEY = "syxlab.live.viewer";
/** The primary detector signal; the wavelength label comes from the instrument. */
const CHROMATOGRAM_STREAM = "DAD1A";

interface StoredSession {
  token: string;
  expires_at: string;
  /** when the session goes live; before that the page waits */
  starts_at?: string | null;
}

function readStored(): StoredSession | null {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const s = JSON.parse(raw) as StoredSession;
    if (!s.token || !s.expires_at || new Date(s.expires_at).getTime() < Date.now()) return null;
    return s;
  } catch {
    return null;
  }
}

function writeStored(s: StoredSession | null): void {
  try {
    if (s) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(s));
    else window.localStorage.removeItem(STORAGE_KEY);
  } catch {
    /* private mode etc. — the session then lasts for this tab only */
  }
}

function fmtWhen(iso: string): string {
  return new Date(iso).toLocaleString([], {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short",
  });
}

function remaining(expiresAt: string | null): string {
  if (!expiresAt) return "";
  const ms = new Date(expiresAt).getTime() - Date.now();
  if (ms <= 0) return "expired";
  const h = Math.floor(ms / 3_600_000);
  const m = Math.floor((ms % 3_600_000) / 60_000);
  return h > 0 ? `${h} h ${m} min` : `${m} min`;
}

function PublicLivePage() {
  // Read the stored token after mount so server and first client render agree.
  const [session, setSession] = useState<StoredSession | null>(null);
  const [ready, setReady] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  // Re-render every 30 s: the "access ends in" label and the switch from
  // "not started yet" to the live viewer both depend on the clock.
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    setSession(readStored());
    setReady(true);
    const t = window.setInterval(() => setNow(Date.now()), 30_000);
    return () => window.clearInterval(t);
  }, []);
  const pending = !!session?.starts_at && new Date(session.starts_at).getTime() > now;

  function signOut(message: string | null) {
    writeStored(null);
    setSession(null);
    setNotice(message);
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border">
        <div className="mx-auto max-w-[1200px] px-4 sm:px-6 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <img src={synthesyxLogo} alt="Synthesyx" className="h-7 w-auto" />
            <div>
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Instruments · Live
              </div>
              <div className="text-sm font-semibold leading-tight">Live Chromatogram</div>
            </div>
          </div>
          {session && (
            <div className="flex items-center gap-3 text-xs text-muted-foreground">
              <span>
                {pending
                  ? `Goes live ${fmtWhen(session.starts_at ?? "")}`
                  : `Access ends in ${remaining(session.expires_at)}`}
              </span>
              <Button variant="outline" size="sm" onClick={() => signOut(null)}>
                <LogOut className="size-3.5" /> Sign out
              </Button>
            </div>
          )}
        </div>
      </header>
      <main className="mx-auto max-w-[1200px] p-4 sm:p-6">
        {!ready ? null : session ? (
          pending ? (
            <WaitingCard startsAt={session.starts_at ?? ""} expiresAt={session.expires_at} />
          ) : (
            <Viewer
              token={session.token}
              onExpired={() =>
                signOut("Your access has ended. Ask for a new passcode to keep watching.")
              }
            />
          )
        ) : (
          <PasscodeGate
            notice={notice}
            onUnlocked={(s) => {
              writeStored(s);
              setNotice(null);
              setSession(s);
            }}
          />
        )}
      </main>
    </div>
  );
}

function WaitingCard({ startsAt, expiresAt }: { startsAt: string; expiresAt: string }) {
  return (
    <div className="mx-auto max-w-md mt-10">
      <Card>
        <CardContent className="pt-6 space-y-3">
          <div className="flex items-center gap-2">
            <KeyRound className="size-5 text-muted-foreground" />
            <h1 className="text-lg font-semibold">Your session hasn't started yet</h1>
          </div>
          <p className="text-sm text-muted-foreground">
            The live chromatogram goes live at {fmtWhen(startsAt)}; this page switches over by
            itself. It stays available until {fmtWhen(expiresAt)}.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

function PasscodeGate({
  notice,
  onUnlocked,
}: {
  notice: string | null;
  onUnlocked: (s: StoredSession) => void;
}) {
  const [code, setCode] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit(e: FormEvent) {
    e.preventDefault();
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/public/live/redeem", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code }),
      });
      const body = (await res.json()) as {
        ok: boolean;
        error?: string;
        token?: string;
        session?: { session_expires_at: string; session_starts_at?: string };
      };
      if (!res.ok || !body.ok || !body.token || !body.session) {
        setError(body.error ?? "Could not unlock the feed.");
        return;
      }
      onUnlocked({
        token: body.token,
        expires_at: body.session.session_expires_at,
        starts_at: body.session.session_starts_at ?? null,
      });
    } catch {
      setError("Could not reach the server. Try again.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mx-auto max-w-md mt-10">
      <Card>
        <CardContent className="pt-6 space-y-4">
          <div className="flex items-center gap-2">
            <KeyRound className="size-5 text-muted-foreground" />
            <h1 className="text-lg font-semibold">Enter your passcode</h1>
          </div>
          <p className="text-sm text-muted-foreground">
            A passcode from Synthesyx shows the live chromatogram on this device until its watch
            session ends. Each passcode works once.
          </p>
          {notice && <div className="text-sm text-muted-foreground">{notice}</div>}
          <form onSubmit={submit} className="space-y-3">
            <div className="space-y-1">
              <Label htmlFor="live-passcode">Passcode</Label>
              <Input
                id="live-passcode"
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder="XXXX-XXXX"
                autoComplete="off"
                autoCapitalize="characters"
                spellCheck={false}
                className="font-mono tracking-widest uppercase"
                autoFocus
              />
            </div>
            {error && <div className="text-sm text-destructive">{error}</div>}
            <Button type="submit" disabled={busy || code.trim().length < 8} className="w-full">
              {busy ? "Checking…" : "Unlock"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

const STREAMS = [CHROMATOGRAM_STREAM];

function Viewer({ token, onExpired }: { token: string; onExpired: () => void }) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const feed = usePublicLiveFeed(token, selectedId, STREAMS);

  useEffect(() => {
    if (feed.expired) onExpired();
  }, [feed.expired, onExpired]);

  const instrument = feed.instruments.find((i) => i.id === feed.instrumentId) ?? null;

  const { series, extent } = useMemo(() => {
    const buf = feed.streams[CHROMATOGRAM_STREAM];
    if (!buf || buf.x.length === 0) return { series: [] as TraceSeries[], extent: null };
    const label = buf.label ? `${CHROMATOGRAM_STREAM} · ${buf.label}` : CHROMATOGRAM_STREAM;
    return {
      series: [
        {
          name: CHROMATOGRAM_STREAM,
          label,
          color: colorForStream(CHROMATOGRAM_STREAM, 0),
          t: buf.x,
          v: buf.v,
        },
      ],
      extent: { lo: buf.x[0], hi: buf.x[buf.x.length - 1] },
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [feed.seq, feed.streams]);

  const win = useLiveWindow(extent);
  const runMarkers = useMemo<RunMarker[]>(
    () =>
      feed.runs.map((r) => ({
        started_at: r.started_at,
        ended_at: r.ended_at,
        label: `injection #${r.injection_index}`,
      })),
    [feed.runs],
  );

  const state = instrument?.status ?? "offline";
  const connected =
    feed.lastPollAt !== null && Date.now() - feed.lastPollAt < 15_000 && !feed.error;
  const emptyText =
    state === "offline"
      ? "Instrument offline — nothing to show."
      : feed.loading
        ? "Loading the last hour…"
        : "Waiting for data…";

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex flex-wrap items-center gap-x-6 gap-y-1 text-sm">
          {feed.instruments.length > 1 ? (
            <Select value={feed.instrumentId ?? ""} onValueChange={setSelectedId}>
              <SelectTrigger className="w-[220px] h-8">
                <SelectValue placeholder="Instrument" />
              </SelectTrigger>
              <SelectContent>
                {feed.instruments.map((i) => (
                  <SelectItem key={i.id} value={i.id}>
                    {i.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          ) : (
            <span className="font-medium">{instrument?.name ?? "—"}</span>
          )}
          <span className="text-muted-foreground">
            {state === "running" ? "Acquiring" : state === "idle" ? "Idle" : "Offline"} · last{" "}
            {LIVE_HISTORY_MINUTES} minutes available
          </span>
        </div>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          {connected ? (
            <Wifi className="size-4 text-[var(--status-success,oklch(0.65_0.15_150))]" />
          ) : (
            <WifiOff className="size-4" />
          )}
          {connected ? "Live" : (feed.error ?? "Connecting…")}
        </div>
      </div>

      {instrument?.sample_name && (
        <div className="px-1 text-lg font-semibold leading-snug">
          {!instrument.running && (
            <span className="mr-2 text-sm font-normal text-muted-foreground">Last run:</span>
          )}
          {instrument.sample_name}
        </div>
      )}

      <TraceChart
        title="Chromatogram"
        unit="mAU"
        series={series}
        height={360}
        emptyText={emptyText}
        xMode="wall"
        xDomain={win.domain}
        runs={runMarkers}
        yFloor={CHROMATOGRAM_Y_FLOOR_MAU}
      />

      <Card>
        <CardContent className="pt-4">
          <LiveWindowControls
            extent={extent}
            win={win}
            note={feed.loading ? "loading history…" : feed.error}
          />
        </CardContent>
      </Card>
    </div>
  );
}
