/**
 * Builds the animation model for a native -> non-conformance transition.
 *
 * Two modes, chosen from the data rather than assumed:
 *
 * - "morph": the impurity was generated by editing the native structure and
 *   relaxing it locally (oxidation, deamidation, disulfide reduction,
 *   deacylation, terminal hydrolysis...). Its coordinates stay in the native
 *   frame, so atoms can be interpolated and the viewer shows a genuine
 *   transformation: an oxygen growing out of a sulfur, a lipid falling away.
 *
 * - "crossfade": a few variants were rebuilt with a full re-embed (the
 *   pyroglutamate ring closures needed one, since a ~4.4 A gap cannot be
 *   closed by local relaxation). Their coordinates are in an unrelated frame,
 *   so interpolating would fling every atom across the screen and invent
 *   motion that never happened. Those dissolve from one form to the other
 *   instead, which is honest about what is and isn't being shown.
 *
 * The mode is decided by RMSD over the atoms common to both structures.
 */
import type { StructureAtom, StructureBond } from "@/lib/nc-structures.functions";

export type MorphAtomState = "persist" | "substituted" | "added" | "removed";
export type MorphBondState = "persist" | "reordered" | "added" | "removed";

export type MorphAtom = {
  /** Unique across the model; also the atom id when it maps 1:1 to a structure atom. */
  key: string;
  /** Structure atom id, or null for the duplicated halves of a crossfade. */
  id: number | null;
  element: string;
  fromElement: string;
  from: [number, number, number];
  to: [number, number, number];
  state: MorphAtomState;
};

export type MorphBond = {
  aKey: string;
  bKey: string;
  state: MorphBondState;
};

export type MorphModel = {
  mode: "morph" | "crossfade";
  atoms: MorphAtom[];
  bonds: MorphBond[];
  /** Heavy-atom RMSD over shared ids, after centering. Drives the mode choice. */
  rmsd: number;
};

type Struct = { atoms: StructureAtom[]; bonds: StructureBond[] };

/** Above this (Angstrom) the two geometries aren't a common frame worth interpolating. */
const MORPH_RMSD_LIMIT = 2.0;

const bkey = (a: number, b: number) => (a < b ? `${a}:${b}` : `${b}:${a}`);
const xyz = (a: StructureAtom): [number, number, number] => [a.x, a.y, a.z];

function centroid(pts: [number, number, number][]): [number, number, number] {
  if (!pts.length) return [0, 0, 0];
  let x = 0;
  let y = 0;
  let z = 0;
  for (const p of pts) {
    x += p[0];
    y += p[1];
    z += p[2];
  }
  return [x / pts.length, y / pts.length, z / pts.length];
}

/**
 * RMSD over shared atom ids after removing the translation difference.
 * No rotational fit: the local-relaxation generators never reorient the
 * molecule, so a large value here means a genuine rebuild, which is exactly
 * the signal we want.
 */
function sharedRmsd(native: Struct, variant: Struct): number {
  const vMap = new Map(variant.atoms.map(a => [a.id, a]));
  const pairs: [[number, number, number], [number, number, number]][] = [];
  for (const n of native.atoms) {
    const v = vMap.get(n.id);
    if (v) pairs.push([xyz(n), xyz(v)]);
  }
  if (!pairs.length) return Number.POSITIVE_INFINITY;

  const cn = centroid(pairs.map(p => p[0]));
  const cv = centroid(pairs.map(p => p[1]));
  let sum = 0;
  for (const [n, v] of pairs) {
    const dx = n[0] - cn[0] - (v[0] - cv[0]);
    const dy = n[1] - cn[1] - (v[1] - cv[1]);
    const dz = n[2] - cn[2] - (v[2] - cv[2]);
    sum += dx * dx + dy * dy + dz * dz;
  }
  return Math.sqrt(sum / pairs.length);
}

function adjacency(bonds: StructureBond[]): Map<number, number[]> {
  const adj = new Map<number, number[]>();
  for (const b of bonds) {
    if (!adj.has(b.a)) adj.set(b.a, []);
    if (!adj.has(b.b)) adj.set(b.b, []);
    adj.get(b.a)!.push(b.b);
    adj.get(b.b)!.push(b.a);
  }
  return adj;
}

export function buildMorph(
  native: Struct | null | undefined,
  variant: Struct | null | undefined,
): MorphModel | null {
  if (!native || !variant) return null;

  const rmsd = sharedRmsd(native, variant);
  if (!Number.isFinite(rmsd) || rmsd > MORPH_RMSD_LIMIT) {
    return crossfadeModel(native, variant, rmsd);
  }

  const nMap = new Map(native.atoms.map(a => [a.id, a]));
  const vMap = new Map(variant.atoms.map(a => [a.id, a]));
  const vAdj = adjacency(variant.bonds);

  const atoms: MorphAtom[] = [];
  const ids = new Set<number>([...nMap.keys(), ...vMap.keys()]);

  for (const id of ids) {
    const n = nMap.get(id);
    const v = vMap.get(id);

    if (n && v) {
      atoms.push({
        key: String(id),
        id,
        element: v.element,
        fromElement: n.element,
        from: xyz(n),
        to: xyz(v),
        state: n.element === v.element ? "persist" : "substituted",
      });
    } else if (v) {
      // An added atom has no native position. Start it on whichever neighbour
      // it bonds to that did exist, so it visibly grows out of its attachment
      // point rather than fading in from nowhere.
      const anchorId = (vAdj.get(id) ?? []).find(p => nMap.has(p));
      const anchor = anchorId !== undefined ? nMap.get(anchorId)! : null;
      atoms.push({
        key: String(id),
        id,
        element: v.element,
        fromElement: v.element,
        from: anchor ? xyz(anchor) : xyz(v),
        to: xyz(v),
        state: "added",
      });
    } else if (n) {
      // Removed atoms fade and shrink where they stand — a cleaved chain
      // dissolving off the parent reads more clearly than one that flies away.
      atoms.push({
        key: String(id),
        id,
        element: n.element,
        fromElement: n.element,
        from: xyz(n),
        to: xyz(n),
        state: "removed",
      });
    }
  }

  const nBonds = new Map(native.bonds.map(b => [bkey(b.a, b.b), b]));
  const vBonds = new Map(variant.bonds.map(b => [bkey(b.a, b.b), b]));
  const bonds: MorphBond[] = [];

  for (const [k, b] of vBonds) {
    const prev = nBonds.get(k);
    bonds.push({
      aKey: String(b.a),
      bKey: String(b.b),
      state: !prev ? "added" : prev.order !== b.order ? "reordered" : "persist",
    });
  }
  for (const [k, b] of nBonds) {
    if (vBonds.has(k)) continue;
    bonds.push({ aKey: String(b.a), bKey: String(b.b), state: "removed" });
  }

  return { mode: "morph", atoms, bonds, rmsd };
}

/**
 * Fallback for rebuilt geometries: render both forms in full and dissolve
 * between them. Reuses the same renderer by expressing the native form as
 * entirely "removed" and the variant as entirely "added".
 *
 * Each half is centred on its own centroid first. Their absolute coordinates
 * are unrelated, so without this the two forms would sit side by side and the
 * dissolve would read as one molecule being swapped for a distant second one.
 */
function crossfadeModel(native: Struct, variant: Struct, rmsd: number): MorphModel {
  const cn = centroid(native.atoms.map(xyz));
  const cv = centroid(variant.atoms.map(xyz));
  const shift = (a: StructureAtom, c: [number, number, number]): [number, number, number] => [
    a.x - c[0],
    a.y - c[1],
    a.z - c[2],
  ];

  const atoms: MorphAtom[] = [
    ...native.atoms.map(a => ({
      key: `n${a.id}`,
      id: a.id,
      element: a.element,
      fromElement: a.element,
      from: shift(a, cn),
      to: shift(a, cn),
      state: "removed" as const,
    })),
    ...variant.atoms.map(a => ({
      key: `v${a.id}`,
      id: a.id,
      element: a.element,
      fromElement: a.element,
      from: shift(a, cv),
      to: shift(a, cv),
      state: "added" as const,
    })),
  ];

  const bonds: MorphBond[] = [
    ...native.bonds.map(b => ({ aKey: `n${b.a}`, bKey: `n${b.b}`, state: "removed" as const })),
    ...variant.bonds.map(b => ({ aKey: `v${b.a}`, bKey: `v${b.b}`, state: "added" as const })),
  ];

  return { mode: "crossfade", atoms, bonds, rmsd };
}
