"""
Generates the Non-Conformity Identifier seed migration SQL from the seven
source reference files. Run once, output is committed as a migration file
— this script is not part of the app runtime.
"""
import csv
import uuid
import sys

NAMESPACE = uuid.UUID("6f1e6b6a-6e1a-4b1a-9c1a-0a1b2c3d4e5f")

FILES = {
    "compound_index": r"C:\Users\dusti\Downloads\Compound_Index_v1.csv",
    "impurity_library": r"C:\Users\dusti\Downloads\Impurity_Library_v1.csv",
    "detection_rules": r"C:\Users\dusti\Downloads\Detection_Rules_v1.csv",
    "oligomer_library": r"C:\Users\dusti\.claude\uploads\788d955c-e9bb-46f9-afbe-95b1f466f3c9\5bfa2d1d-Oligomer_Library_v1.csv",
    "oligomer_detection_rules": r"C:\Users\dusti\.claude\uploads\788d955c-e9bb-46f9-afbe-95b1f466f3c9\6a4509fe-Oligomer_Detection_Rules_v11.csv",
    "oligomer_evidence_rules": r"C:\Users\dusti\.claude\uploads\788d955c-e9bb-46f9-afbe-95b1f466f3c9\4659f95b-Oligomer_Evidence_Rules_v1.csv",
    "spectral_panels": r"C:\Users\dusti\.claude\uploads\788d955c-e9bb-46f9-afbe-95b1f466f3c9\6b192bcc-Spectral_Panels_v1.csv",
}


def compound_id(name: str) -> str:
    return str(uuid.uuid5(NAMESPACE, name.strip()))


def sql_str(v):
    if v is None:
        return "NULL"
    v = str(v).strip()
    if v == "":
        return "NULL"
    return "'" + v.replace("'", "''") + "'"


def sql_num(v):
    if v is None:
        return "NULL"
    v = str(v).strip()
    if v == "":
        return "NULL"
    try:
        float(v)
    except ValueError:
        return "NULL"
    return v


def read_rows(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not any((v or "").strip() for v in row.values()):
                continue
            yield row


def main():
    out = []
    out.append("-- Non-Conformity Identifier seed data, generated by scripts/generate_nc_seed.py")
    out.append("-- from the seven supplied reference files. Do not hand-edit; regenerate instead.\n")

    # --- nc_compounds ---
    compound_names = set()
    out.append("-- nc_compounds")
    for row in read_rows(FILES["compound_index"]):
        name = row["Compound"].strip()
        compound_names.add(name)
        cid = compound_id(name)
        out.append(
            "INSERT INTO public.nc_compounds "
            "(id, name, class, sequence_composition, amino_acid_composition, molecular_formula, "
            "monoisotopic_mass, mz_1plus, mz_2plus, cas_number, dad_primary, dad_secondary, "
            "dad_guidance, key_chromophores, form_notes, review_flag, source_url) VALUES ("
            f"{sql_str(cid)}, {sql_str(name)}, {sql_str(row['Class'])}, "
            f"{sql_str(row['Sequence / composition'])}, {sql_str(row['Amino-acid composition'])}, "
            f"{sql_str(row['Molecular formula'])}, {sql_num(row['Monoisotopic mass (Da)'])}, "
            f"{sql_num(row['[M+H]+ (m/z)'])}, {sql_num(row['[M+2H]2+ (m/z)'])}, {sql_str(row['CAS'])}, "
            f"{sql_str(row['DAD primary'])}, {sql_str(row['DAD secondary'])}, "
            f"{sql_str(row['DAD / UV identity guidance'])}, {sql_str(row['Key chromophore(s)'])}, "
            f"{sql_str(row['Form / identity notes'])}, {sql_str(row['Review flag'])}, "
            f"{sql_str(row['Parent source URL'])});"
        )

    # --- nc_impurity_candidates ---
    out.append("\n-- nc_impurity_candidates")
    for row in read_rows(FILES["impurity_library"]):
        parent = row["Parent compound"].strip()
        if parent not in compound_names:
            print(f"WARNING: impurity row references unknown compound {parent!r}", file=sys.stderr)
            continue
        out.append(
            "INSERT INTO public.nc_impurity_candidates "
            "(nc_compound_id, impurity_code, name, category, evidence_level, formation_pathway, "
            "structure_change, molecular_formula, formula_delta, monoisotopic_mass, mass_delta, "
            "mz_1plus, mz_2plus, dad_primary, dad_secondary, dad_discriminator, rp_hplc_behavior, "
            "lc_ms_discriminator, likely_trigger, source_url, notes) VALUES ("
            f"{sql_str(compound_id(parent))}, {sql_str(row['Impurity ID'])}, {sql_str(row['Impurity / candidate'])}, "
            f"{sql_str(row['Category'])}, {sql_str(row['Evidence level'])}, {sql_str(row['Formation pathway'])}, "
            f"{sql_str(row['Sequence / structure change'])}, {sql_str(row['Molecular formula'])}, "
            f"{sql_str(row['Formula delta'])}, {sql_num(row['Neutral monoisotopic mass (Da)'])}, "
            f"{sql_num(row['Delta mass vs parent (Da)'])}, {sql_num(row['[M+H]+ expected (m/z)'])}, "
            f"{sql_num(row['[M+2H]2+ expected (m/z)'])}, {sql_str(row['DAD primary / screening'])}, "
            f"{sql_str(row['DAD secondary / diagnostic'])}, {sql_str(row['DAD / UV discriminator'])}, "
            f"{sql_str(row['RP-HPLC retention vs parent'])}, {sql_str(row['LC-MS discriminator'])}, "
            f"{sql_str(row['Likely trigger / context'])}, {sql_str(row['Source URL'])}, {sql_str(row['Notes'])});"
        )

    # --- nc_detection_rules (impurity kind) ---
    out.append("\n-- nc_detection_rules (impurity)")
    for row in read_rows(FILES["detection_rules"]):
        out.append(
            "INSERT INTO public.nc_detection_rules "
            "(rule_id, kind, applies_to, trigger_feature, candidate_product, formula_delta, mass_delta, "
            "rp_hplc_behavior, dad_behavior, evidence_level, source_url, notes) VALUES ("
            f"{sql_str(row['Rule ID'])}, 'impurity', {sql_str(row['Applies to'])}, "
            f"{sql_str(row['Trigger motif / feature'])}, {sql_str(row['Candidate product'])}, "
            f"{sql_str(row['Formula delta'])}, {sql_num(row['Mass delta (Da)'])}, "
            f"{sql_str(row['Typical RP-HPLC behavior'])}, {sql_str(row['DAD behavior'])}, "
            f"{sql_str(row['Evidence level'])}, {sql_str(row['Source URL'])}, {sql_str(row['Notes'])});"
        )

    # --- nc_oligomer_candidates ---
    out.append("\n-- nc_oligomer_candidates")
    for row in read_rows(FILES["oligomer_library"]):
        parent = row["Parent compound"].strip()
        if parent not in compound_names:
            print(f"WARNING: oligomer row references unknown compound {parent!r}", file=sys.stderr)
            continue
        out.append(
            "INSERT INTO public.nc_oligomer_candidates "
            "(nc_compound_id, oligomer_code, name, class, stoichiometry, evidence_level, mechanism_pathway, "
            "trigger_motif, molecular_formula, monoisotopic_mass, mass_delta_vs_n_monomer, mz_1plus, mz_2plus, "
            "other_diagnostic_ions, expected_normalized_dad, dad_discriminator, rp_hplc_behavior, "
            "best_orthogonal_discriminator, lc_ms_discriminator, false_positive_warning, source_url, notes) VALUES ("
            f"{sql_str(compound_id(parent))}, {sql_str(row['Oligomer ID'])}, {sql_str(row['Candidate / phenomenon'])}, "
            f"{sql_str(row['Class'])}, {sql_str(row['Stoichiometry'])}, {sql_str(row['Evidence level'])}, "
            f"{sql_str(row['Mechanism / pathway'])}, {sql_str(row['Trigger motif / feature'])}, "
            f"{sql_str(row['Molecular formula (if defined)'])}, {sql_num(row['Neutral monoisotopic mass (Da)'])}, "
            f"{sql_num(row['Delta vs n x monomer (Da)'])}, {sql_num(row['[candidate+H]+ expected (m/z)'])}, "
            f"{sql_num(row['[candidate+2H]2+ expected (m/z)'])}, {sql_str(row['Other diagnostic ions / charge-state clue'])}, "
            f"{sql_str(row['Expected normalized DAD spectrum vs monomer'])}, {sql_str(row['DAD / full-spectrum discriminator'])}, "
            f"{sql_str(row['RP-HPLC behavior'])}, {sql_str(row['Best orthogonal discriminator'])}, "
            f"{sql_str(row['LC-MS discriminator'])}, {sql_str(row['False-positive / interpretation warning'])}, "
            f"{sql_str(row['Source URL'])}, {sql_str(row['Notes'])});"
        )

    # --- nc_detection_rules (oligomer kind) ---
    out.append("\n-- nc_detection_rules (oligomer)")
    for row in read_rows(FILES["oligomer_detection_rules"]):
        out.append(
            "INSERT INTO public.nc_detection_rules "
            "(rule_id, kind, applies_to, trigger_feature, candidate_product, rp_hplc_behavior, dad_behavior, "
            "discriminator, guardrail, evidence_level, source_url) VALUES ("
            f"{sql_str(row['Rule ID'])}, 'oligomer', {sql_str(row['Applies to'])}, {sql_str(row['Trigger'])}, "
            f"{sql_str(row['Candidate'])}, {sql_str(row['Mass relationship'])}, "
            f"{sql_str(row['DAD/full-spectrum expectation'])}, {sql_str(row['Discriminator'])}, "
            f"{sql_str(row['LIMS guardrail'])}, {sql_str(row['Evidence level'])}, {sql_str(row['Source URL'])});"
        )

    # --- nc_evidence_rules ---
    out.append("\n-- nc_evidence_rules")
    for row in read_rows(FILES["oligomer_evidence_rules"]):
        out.append(
            "INSERT INTO public.nc_evidence_rules "
            "(rule_id, observation, suggested_score_effect, interpretation_guardrail) VALUES ("
            f"{sql_str(row['Rule ID'])}, {sql_str(row['Observation'])}, {sql_str(row['Suggested score effect'])}, "
            f"{sql_str(row['Interpretation / guardrail'])});"
        )

    # --- nc_spectral_panels ---
    out.append("\n-- nc_spectral_panels")
    for row in read_rows(FILES["spectral_panels"]):
        name = row["Compound"].strip()
        if name not in compound_names:
            print(f"WARNING: spectral panel row references unknown compound {name!r}", file=sys.stderr)
            continue
        wavelengths = []
        for i in range(1, 9):
            v = row.get(f"Wavelength {i} (nm)", "").strip()
            if v:
                wavelengths.append(v)
        arr = "ARRAY[" + ",".join(wavelengths) + "]::integer[]" if wavelengths else "ARRAY[]::integer[]"
        out.append(
            "INSERT INTO public.nc_spectral_panels "
            "(nc_compound_id, wavelengths_nm, recommended_range, panel_rationale, recommended_features, "
            "parent_dad_guidance, important_note) VALUES ("
            f"{sql_str(compound_id(name))}, {arr}, {sql_str(row['Recommended full-spectrum range'])}, "
            f"{sql_str(row['Panel rationale'])}, {sql_str(row['Recommended spectral features'])}, "
            f"{sql_str(row['Parent DAD guidance'])}, {sql_str(row['Important note'])});"
        )

    print("\n".join(out))


if __name__ == "__main__":
    main()
