/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedChainOfCustodyRouteImport } from './routes/_authenticated/chain-of-custody'
import { Route as AuthenticatedSchedulerIndexRouteImport } from './routes/_authenticated/scheduler/index'
import { Route as AuthenticatedSamplesIndexRouteImport } from './routes/_authenticated/samples/index'
import { Route as AuthenticatedRunListsIndexRouteImport } from './routes/_authenticated/run-lists/index'
import { Route as AuthenticatedMaterialReceiptsIndexRouteImport } from './routes/_authenticated/material-receipts/index'
import { Route as AuthenticatedLabLogsIndexRouteImport } from './routes/_authenticated/lab-logs/index'
import { Route as AuthenticatedLabJournalIndexRouteImport } from './routes/_authenticated/lab-journal/index'
import { Route as AuthenticatedIssuesIndexRouteImport } from './routes/_authenticated/issues/index'
import { Route as AuthenticatedInstrumentCommIndexRouteImport } from './routes/_authenticated/instrument-comm/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSamplesNewRouteImport } from './routes/_authenticated/samples/new'
import { Route as AuthenticatedSamplesBatchIdRouteImport } from './routes/_authenticated/samples/$batchId'
import { Route as AuthenticatedRunListsIdRouteImport } from './routes/_authenticated/run-lists/$id'
import { Route as AuthenticatedMaterialReceiptsNewRouteImport } from './routes/_authenticated/material-receipts/new'
import { Route as AuthenticatedMaterialReceiptsAccountingReportRouteImport } from './routes/_authenticated/material-receipts/accounting-report'
import { Route as AuthenticatedMaterialReceiptsIdRouteImport } from './routes/_authenticated/material-receipts/$id'
import { Route as AuthenticatedInstrumentCommOpenlabRouteImport } from './routes/_authenticated/instrument-comm/openlab'
import { Route as AuthenticatedAdminTimesheetProjectsRouteImport } from './routes/_authenticated/admin/timesheet-projects'
import { Route as AuthenticatedAdminRunListColumnsRouteImport } from './routes/_authenticated/admin/run-list-columns'
import { Route as AuthenticatedAdminParametersRouteImport } from './routes/_authenticated/admin/parameters'
import { Route as AuthenticatedAdminMobilePhaseReagentsRouteImport } from './routes/_authenticated/admin/mobile-phase-reagents'
import { Route as AuthenticatedAdminInstrumentsRouteImport } from './routes/_authenticated/admin/instruments'
import { Route as AuthenticatedAdminHplcColumnsRouteImport } from './routes/_authenticated/admin/hplc-columns'
import { Route as AuthenticatedAdminCompoundsRouteImport } from './routes/_authenticated/admin/compounds'
import { Route as AuthenticatedAdminCocFieldsRouteImport } from './routes/_authenticated/admin/coc-fields'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminAccessLogsRouteImport } from './routes/_authenticated/admin/access-logs'
import { Route as AuthenticatedLabLogsTimesheetsIndexRouteImport } from './routes/_authenticated/lab-logs/timesheets/index'
import { Route as AuthenticatedLabLogsStandardPreparationsIndexRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/index'
import { Route as AuthenticatedLabLogsParameterScoutingIndexRouteImport } from './routes/_authenticated/lab-logs/parameter-scouting/index'
import { Route as AuthenticatedLabLogsMobilePhaseIndexRouteImport } from './routes/_authenticated/lab-logs/mobile-phase/index'
import { Route as AuthenticatedLabLogsDailyBackpressureIndexRouteImport } from './routes/_authenticated/lab-logs/daily-backpressure/index'
import { Route as ApiPublicExportsBatchIdRouteImport } from './routes/api/public/exports/$batchId'
import { Route as AuthenticatedLabLogsTimesheetsReportsRouteImport } from './routes/_authenticated/lab-logs/timesheets/reports'
import { Route as AuthenticatedLabLogsTimesheetsHistoryRouteImport } from './routes/_authenticated/lab-logs/timesheets/history'
import { Route as AuthenticatedLabLogsTimesheetsDailyRouteImport } from './routes/_authenticated/lab-logs/timesheets/daily'
import { Route as AuthenticatedLabLogsStandardPreparationsNewRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/new'
import { Route as AuthenticatedLabLogsStandardPreparationsIdRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/$id'
import { Route as AuthenticatedLabLogsMobilePhaseNewRouteImport } from './routes/_authenticated/lab-logs/mobile-phase/new'
import { Route as AuthenticatedLabLogsMobilePhaseIdRouteImport } from './routes/_authenticated/lab-logs/mobile-phase/$id'
import { Route as AuthenticatedLabLogsStandardPreparationsBatchGroupIdRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/batch.$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChainOfCustodyRoute =
  AuthenticatedChainOfCustodyRouteImport.update({
    id: '/chain-of-custody',
    path: '/chain-of-custody',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchedulerIndexRoute =
  AuthenticatedSchedulerIndexRouteImport.update({
    id: '/scheduler/',
    path: '/scheduler/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesIndexRoute =
  AuthenticatedSamplesIndexRouteImport.update({
    id: '/samples/',
    path: '/samples/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunListsIndexRoute =
  AuthenticatedRunListsIndexRouteImport.update({
    id: '/run-lists/',
    path: '/run-lists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialReceiptsIndexRoute =
  AuthenticatedMaterialReceiptsIndexRouteImport.update({
    id: '/material-receipts/',
    path: '/material-receipts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsIndexRoute =
  AuthenticatedLabLogsIndexRouteImport.update({
    id: '/lab-logs/',
    path: '/lab-logs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabJournalIndexRoute =
  AuthenticatedLabJournalIndexRouteImport.update({
    id: '/lab-journal/',
    path: '/lab-journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIndexRoute =
  AuthenticatedIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrumentCommIndexRoute =
  AuthenticatedInstrumentCommIndexRouteImport.update({
    id: '/instrument-comm/',
    path: '/instrument-comm/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesNewRoute = AuthenticatedSamplesNewRouteImport.update({
  id: '/samples/new',
  path: '/samples/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesBatchIdRoute =
  AuthenticatedSamplesBatchIdRouteImport.update({
    id: '/samples/$batchId',
    path: '/samples/$batchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunListsIdRoute = AuthenticatedRunListsIdRouteImport.update({
  id: '/run-lists/$id',
  path: '/run-lists/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialReceiptsNewRoute =
  AuthenticatedMaterialReceiptsNewRouteImport.update({
    id: '/material-receipts/new',
    path: '/material-receipts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialReceiptsAccountingReportRoute =
  AuthenticatedMaterialReceiptsAccountingReportRouteImport.update({
    id: '/material-receipts/accounting-report',
    path: '/material-receipts/accounting-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialReceiptsIdRoute =
  AuthenticatedMaterialReceiptsIdRouteImport.update({
    id: '/material-receipts/$id',
    path: '/material-receipts/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrumentCommOpenlabRoute =
  AuthenticatedInstrumentCommOpenlabRouteImport.update({
    id: '/instrument-comm/openlab',
    path: '/instrument-comm/openlab',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTimesheetProjectsRoute =
  AuthenticatedAdminTimesheetProjectsRouteImport.update({
    id: '/admin/timesheet-projects',
    path: '/admin/timesheet-projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRunListColumnsRoute =
  AuthenticatedAdminRunListColumnsRouteImport.update({
    id: '/admin/run-list-columns',
    path: '/admin/run-list-columns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminParametersRoute =
  AuthenticatedAdminParametersRouteImport.update({
    id: '/admin/parameters',
    path: '/admin/parameters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMobilePhaseReagentsRoute =
  AuthenticatedAdminMobilePhaseReagentsRouteImport.update({
    id: '/admin/mobile-phase-reagents',
    path: '/admin/mobile-phase-reagents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInstrumentsRoute =
  AuthenticatedAdminInstrumentsRouteImport.update({
    id: '/admin/instruments',
    path: '/admin/instruments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHplcColumnsRoute =
  AuthenticatedAdminHplcColumnsRouteImport.update({
    id: '/admin/hplc-columns',
    path: '/admin/hplc-columns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCompoundsRoute =
  AuthenticatedAdminCompoundsRouteImport.update({
    id: '/admin/compounds',
    path: '/admin/compounds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCocFieldsRoute =
  AuthenticatedAdminCocFieldsRouteImport.update({
    id: '/admin/coc-fields',
    path: '/admin/coc-fields',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAccessLogsRoute =
  AuthenticatedAdminAccessLogsRouteImport.update({
    id: '/admin/access-logs',
    path: '/admin/access-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsTimesheetsIndexRoute =
  AuthenticatedLabLogsTimesheetsIndexRouteImport.update({
    id: '/lab-logs/timesheets/',
    path: '/lab-logs/timesheets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsIndexRoute =
  AuthenticatedLabLogsStandardPreparationsIndexRouteImport.update({
    id: '/lab-logs/standard-preparations/',
    path: '/lab-logs/standard-preparations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsParameterScoutingIndexRoute =
  AuthenticatedLabLogsParameterScoutingIndexRouteImport.update({
    id: '/lab-logs/parameter-scouting/',
    path: '/lab-logs/parameter-scouting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsMobilePhaseIndexRoute =
  AuthenticatedLabLogsMobilePhaseIndexRouteImport.update({
    id: '/lab-logs/mobile-phase/',
    path: '/lab-logs/mobile-phase/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsDailyBackpressureIndexRoute =
  AuthenticatedLabLogsDailyBackpressureIndexRouteImport.update({
    id: '/lab-logs/daily-backpressure/',
    path: '/lab-logs/daily-backpressure/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicExportsBatchIdRoute = ApiPublicExportsBatchIdRouteImport.update({
  id: '/api/public/exports/$batchId',
  path: '/api/public/exports/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLabLogsTimesheetsReportsRoute =
  AuthenticatedLabLogsTimesheetsReportsRouteImport.update({
    id: '/lab-logs/timesheets/reports',
    path: '/lab-logs/timesheets/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsTimesheetsHistoryRoute =
  AuthenticatedLabLogsTimesheetsHistoryRouteImport.update({
    id: '/lab-logs/timesheets/history',
    path: '/lab-logs/timesheets/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsTimesheetsDailyRoute =
  AuthenticatedLabLogsTimesheetsDailyRouteImport.update({
    id: '/lab-logs/timesheets/daily',
    path: '/lab-logs/timesheets/daily',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsNewRoute =
  AuthenticatedLabLogsStandardPreparationsNewRouteImport.update({
    id: '/lab-logs/standard-preparations/new',
    path: '/lab-logs/standard-preparations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsIdRoute =
  AuthenticatedLabLogsStandardPreparationsIdRouteImport.update({
    id: '/lab-logs/standard-preparations/$id',
    path: '/lab-logs/standard-preparations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsMobilePhaseNewRoute =
  AuthenticatedLabLogsMobilePhaseNewRouteImport.update({
    id: '/lab-logs/mobile-phase/new',
    path: '/lab-logs/mobile-phase/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsMobilePhaseIdRoute =
  AuthenticatedLabLogsMobilePhaseIdRouteImport.update({
    id: '/lab-logs/mobile-phase/$id',
    path: '/lab-logs/mobile-phase/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute =
  AuthenticatedLabLogsStandardPreparationsBatchGroupIdRouteImport.update({
    id: '/lab-logs/standard-preparations/batch/$groupId',
    path: '/lab-logs/standard-preparations/batch/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/chain-of-custody': typeof AuthenticatedChainOfCustodyRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/access-logs': typeof AuthenticatedAdminAccessLogsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/coc-fields': typeof AuthenticatedAdminCocFieldsRoute
  '/admin/compounds': typeof AuthenticatedAdminCompoundsRoute
  '/admin/hplc-columns': typeof AuthenticatedAdminHplcColumnsRoute
  '/admin/instruments': typeof AuthenticatedAdminInstrumentsRoute
  '/admin/mobile-phase-reagents': typeof AuthenticatedAdminMobilePhaseReagentsRoute
  '/admin/parameters': typeof AuthenticatedAdminParametersRoute
  '/admin/run-list-columns': typeof AuthenticatedAdminRunListColumnsRoute
  '/admin/timesheet-projects': typeof AuthenticatedAdminTimesheetProjectsRoute
  '/instrument-comm/openlab': typeof AuthenticatedInstrumentCommOpenlabRoute
  '/material-receipts/$id': typeof AuthenticatedMaterialReceiptsIdRoute
  '/material-receipts/accounting-report': typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  '/material-receipts/new': typeof AuthenticatedMaterialReceiptsNewRoute
  '/run-lists/$id': typeof AuthenticatedRunListsIdRoute
  '/samples/$batchId': typeof AuthenticatedSamplesBatchIdRoute
  '/samples/new': typeof AuthenticatedSamplesNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/instrument-comm/': typeof AuthenticatedInstrumentCommIndexRoute
  '/issues/': typeof AuthenticatedIssuesIndexRoute
  '/lab-journal/': typeof AuthenticatedLabJournalIndexRoute
  '/lab-logs/': typeof AuthenticatedLabLogsIndexRoute
  '/material-receipts/': typeof AuthenticatedMaterialReceiptsIndexRoute
  '/run-lists/': typeof AuthenticatedRunListsIndexRoute
  '/samples/': typeof AuthenticatedSamplesIndexRoute
  '/scheduler/': typeof AuthenticatedSchedulerIndexRoute
  '/lab-logs/mobile-phase/$id': typeof AuthenticatedLabLogsMobilePhaseIdRoute
  '/lab-logs/mobile-phase/new': typeof AuthenticatedLabLogsMobilePhaseNewRoute
  '/lab-logs/standard-preparations/$id': typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  '/lab-logs/standard-preparations/new': typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  '/lab-logs/timesheets/daily': typeof AuthenticatedLabLogsTimesheetsDailyRoute
  '/lab-logs/timesheets/history': typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  '/lab-logs/timesheets/reports': typeof AuthenticatedLabLogsTimesheetsReportsRoute
  '/api/public/exports/$batchId': typeof ApiPublicExportsBatchIdRoute
  '/lab-logs/daily-backpressure/': typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  '/lab-logs/mobile-phase/': typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  '/lab-logs/parameter-scouting/': typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  '/lab-logs/standard-preparations/': typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  '/lab-logs/timesheets/': typeof AuthenticatedLabLogsTimesheetsIndexRoute
  '/lab-logs/standard-preparations/batch/$groupId': typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/chain-of-custody': typeof AuthenticatedChainOfCustodyRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/access-logs': typeof AuthenticatedAdminAccessLogsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/coc-fields': typeof AuthenticatedAdminCocFieldsRoute
  '/admin/compounds': typeof AuthenticatedAdminCompoundsRoute
  '/admin/hplc-columns': typeof AuthenticatedAdminHplcColumnsRoute
  '/admin/instruments': typeof AuthenticatedAdminInstrumentsRoute
  '/admin/mobile-phase-reagents': typeof AuthenticatedAdminMobilePhaseReagentsRoute
  '/admin/parameters': typeof AuthenticatedAdminParametersRoute
  '/admin/run-list-columns': typeof AuthenticatedAdminRunListColumnsRoute
  '/admin/timesheet-projects': typeof AuthenticatedAdminTimesheetProjectsRoute
  '/instrument-comm/openlab': typeof AuthenticatedInstrumentCommOpenlabRoute
  '/material-receipts/$id': typeof AuthenticatedMaterialReceiptsIdRoute
  '/material-receipts/accounting-report': typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  '/material-receipts/new': typeof AuthenticatedMaterialReceiptsNewRoute
  '/run-lists/$id': typeof AuthenticatedRunListsIdRoute
  '/samples/$batchId': typeof AuthenticatedSamplesBatchIdRoute
  '/samples/new': typeof AuthenticatedSamplesNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/instrument-comm': typeof AuthenticatedInstrumentCommIndexRoute
  '/issues': typeof AuthenticatedIssuesIndexRoute
  '/lab-journal': typeof AuthenticatedLabJournalIndexRoute
  '/lab-logs': typeof AuthenticatedLabLogsIndexRoute
  '/material-receipts': typeof AuthenticatedMaterialReceiptsIndexRoute
  '/run-lists': typeof AuthenticatedRunListsIndexRoute
  '/samples': typeof AuthenticatedSamplesIndexRoute
  '/scheduler': typeof AuthenticatedSchedulerIndexRoute
  '/lab-logs/mobile-phase/$id': typeof AuthenticatedLabLogsMobilePhaseIdRoute
  '/lab-logs/mobile-phase/new': typeof AuthenticatedLabLogsMobilePhaseNewRoute
  '/lab-logs/standard-preparations/$id': typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  '/lab-logs/standard-preparations/new': typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  '/lab-logs/timesheets/daily': typeof AuthenticatedLabLogsTimesheetsDailyRoute
  '/lab-logs/timesheets/history': typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  '/lab-logs/timesheets/reports': typeof AuthenticatedLabLogsTimesheetsReportsRoute
  '/api/public/exports/$batchId': typeof ApiPublicExportsBatchIdRoute
  '/lab-logs/daily-backpressure': typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  '/lab-logs/mobile-phase': typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  '/lab-logs/parameter-scouting': typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  '/lab-logs/standard-preparations': typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  '/lab-logs/timesheets': typeof AuthenticatedLabLogsTimesheetsIndexRoute
  '/lab-logs/standard-preparations/batch/$groupId': typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/chain-of-custody': typeof AuthenticatedChainOfCustodyRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/access-logs': typeof AuthenticatedAdminAccessLogsRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/coc-fields': typeof AuthenticatedAdminCocFieldsRoute
  '/_authenticated/admin/compounds': typeof AuthenticatedAdminCompoundsRoute
  '/_authenticated/admin/hplc-columns': typeof AuthenticatedAdminHplcColumnsRoute
  '/_authenticated/admin/instruments': typeof AuthenticatedAdminInstrumentsRoute
  '/_authenticated/admin/mobile-phase-reagents': typeof AuthenticatedAdminMobilePhaseReagentsRoute
  '/_authenticated/admin/parameters': typeof AuthenticatedAdminParametersRoute
  '/_authenticated/admin/run-list-columns': typeof AuthenticatedAdminRunListColumnsRoute
  '/_authenticated/admin/timesheet-projects': typeof AuthenticatedAdminTimesheetProjectsRoute
  '/_authenticated/instrument-comm/openlab': typeof AuthenticatedInstrumentCommOpenlabRoute
  '/_authenticated/material-receipts/$id': typeof AuthenticatedMaterialReceiptsIdRoute
  '/_authenticated/material-receipts/accounting-report': typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  '/_authenticated/material-receipts/new': typeof AuthenticatedMaterialReceiptsNewRoute
  '/_authenticated/run-lists/$id': typeof AuthenticatedRunListsIdRoute
  '/_authenticated/samples/$batchId': typeof AuthenticatedSamplesBatchIdRoute
  '/_authenticated/samples/new': typeof AuthenticatedSamplesNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/instrument-comm/': typeof AuthenticatedInstrumentCommIndexRoute
  '/_authenticated/issues/': typeof AuthenticatedIssuesIndexRoute
  '/_authenticated/lab-journal/': typeof AuthenticatedLabJournalIndexRoute
  '/_authenticated/lab-logs/': typeof AuthenticatedLabLogsIndexRoute
  '/_authenticated/material-receipts/': typeof AuthenticatedMaterialReceiptsIndexRoute
  '/_authenticated/run-lists/': typeof AuthenticatedRunListsIndexRoute
  '/_authenticated/samples/': typeof AuthenticatedSamplesIndexRoute
  '/_authenticated/scheduler/': typeof AuthenticatedSchedulerIndexRoute
  '/_authenticated/lab-logs/mobile-phase/$id': typeof AuthenticatedLabLogsMobilePhaseIdRoute
  '/_authenticated/lab-logs/mobile-phase/new': typeof AuthenticatedLabLogsMobilePhaseNewRoute
  '/_authenticated/lab-logs/standard-preparations/$id': typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  '/_authenticated/lab-logs/standard-preparations/new': typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  '/_authenticated/lab-logs/timesheets/daily': typeof AuthenticatedLabLogsTimesheetsDailyRoute
  '/_authenticated/lab-logs/timesheets/history': typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  '/_authenticated/lab-logs/timesheets/reports': typeof AuthenticatedLabLogsTimesheetsReportsRoute
  '/api/public/exports/$batchId': typeof ApiPublicExportsBatchIdRoute
  '/_authenticated/lab-logs/daily-backpressure/': typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  '/_authenticated/lab-logs/mobile-phase/': typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  '/_authenticated/lab-logs/parameter-scouting/': typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  '/_authenticated/lab-logs/standard-preparations/': typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  '/_authenticated/lab-logs/timesheets/': typeof AuthenticatedLabLogsTimesheetsIndexRoute
  '/_authenticated/lab-logs/standard-preparations/batch/$groupId': typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chain-of-custody'
    | '/intake'
    | '/integrations'
    | '/users'
    | '/admin/access-logs'
    | '/admin/audit-log'
    | '/admin/coc-fields'
    | '/admin/compounds'
    | '/admin/hplc-columns'
    | '/admin/instruments'
    | '/admin/mobile-phase-reagents'
    | '/admin/parameters'
    | '/admin/run-list-columns'
    | '/admin/timesheet-projects'
    | '/instrument-comm/openlab'
    | '/material-receipts/$id'
    | '/material-receipts/accounting-report'
    | '/material-receipts/new'
    | '/run-lists/$id'
    | '/samples/$batchId'
    | '/samples/new'
    | '/admin/'
    | '/clients/'
    | '/instrument-comm/'
    | '/issues/'
    | '/lab-journal/'
    | '/lab-logs/'
    | '/material-receipts/'
    | '/run-lists/'
    | '/samples/'
    | '/scheduler/'
    | '/lab-logs/mobile-phase/$id'
    | '/lab-logs/mobile-phase/new'
    | '/lab-logs/standard-preparations/$id'
    | '/lab-logs/standard-preparations/new'
    | '/lab-logs/timesheets/daily'
    | '/lab-logs/timesheets/history'
    | '/lab-logs/timesheets/reports'
    | '/api/public/exports/$batchId'
    | '/lab-logs/daily-backpressure/'
    | '/lab-logs/mobile-phase/'
    | '/lab-logs/parameter-scouting/'
    | '/lab-logs/standard-preparations/'
    | '/lab-logs/timesheets/'
    | '/lab-logs/standard-preparations/batch/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/chain-of-custody'
    | '/intake'
    | '/integrations'
    | '/users'
    | '/'
    | '/admin/access-logs'
    | '/admin/audit-log'
    | '/admin/coc-fields'
    | '/admin/compounds'
    | '/admin/hplc-columns'
    | '/admin/instruments'
    | '/admin/mobile-phase-reagents'
    | '/admin/parameters'
    | '/admin/run-list-columns'
    | '/admin/timesheet-projects'
    | '/instrument-comm/openlab'
    | '/material-receipts/$id'
    | '/material-receipts/accounting-report'
    | '/material-receipts/new'
    | '/run-lists/$id'
    | '/samples/$batchId'
    | '/samples/new'
    | '/admin'
    | '/clients'
    | '/instrument-comm'
    | '/issues'
    | '/lab-journal'
    | '/lab-logs'
    | '/material-receipts'
    | '/run-lists'
    | '/samples'
    | '/scheduler'
    | '/lab-logs/mobile-phase/$id'
    | '/lab-logs/mobile-phase/new'
    | '/lab-logs/standard-preparations/$id'
    | '/lab-logs/standard-preparations/new'
    | '/lab-logs/timesheets/daily'
    | '/lab-logs/timesheets/history'
    | '/lab-logs/timesheets/reports'
    | '/api/public/exports/$batchId'
    | '/lab-logs/daily-backpressure'
    | '/lab-logs/mobile-phase'
    | '/lab-logs/parameter-scouting'
    | '/lab-logs/standard-preparations'
    | '/lab-logs/timesheets'
    | '/lab-logs/standard-preparations/batch/$groupId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/chain-of-custody'
    | '/_authenticated/intake'
    | '/_authenticated/integrations'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/admin/access-logs'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/coc-fields'
    | '/_authenticated/admin/compounds'
    | '/_authenticated/admin/hplc-columns'
    | '/_authenticated/admin/instruments'
    | '/_authenticated/admin/mobile-phase-reagents'
    | '/_authenticated/admin/parameters'
    | '/_authenticated/admin/run-list-columns'
    | '/_authenticated/admin/timesheet-projects'
    | '/_authenticated/instrument-comm/openlab'
    | '/_authenticated/material-receipts/$id'
    | '/_authenticated/material-receipts/accounting-report'
    | '/_authenticated/material-receipts/new'
    | '/_authenticated/run-lists/$id'
    | '/_authenticated/samples/$batchId'
    | '/_authenticated/samples/new'
    | '/_authenticated/admin/'
    | '/_authenticated/clients/'
    | '/_authenticated/instrument-comm/'
    | '/_authenticated/issues/'
    | '/_authenticated/lab-journal/'
    | '/_authenticated/lab-logs/'
    | '/_authenticated/material-receipts/'
    | '/_authenticated/run-lists/'
    | '/_authenticated/samples/'
    | '/_authenticated/scheduler/'
    | '/_authenticated/lab-logs/mobile-phase/$id'
    | '/_authenticated/lab-logs/mobile-phase/new'
    | '/_authenticated/lab-logs/standard-preparations/$id'
    | '/_authenticated/lab-logs/standard-preparations/new'
    | '/_authenticated/lab-logs/timesheets/daily'
    | '/_authenticated/lab-logs/timesheets/history'
    | '/_authenticated/lab-logs/timesheets/reports'
    | '/api/public/exports/$batchId'
    | '/_authenticated/lab-logs/daily-backpressure/'
    | '/_authenticated/lab-logs/mobile-phase/'
    | '/_authenticated/lab-logs/parameter-scouting/'
    | '/_authenticated/lab-logs/standard-preparations/'
    | '/_authenticated/lab-logs/timesheets/'
    | '/_authenticated/lab-logs/standard-preparations/batch/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicExportsBatchIdRoute: typeof ApiPublicExportsBatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chain-of-custody': {
      id: '/_authenticated/chain-of-custody'
      path: '/chain-of-custody'
      fullPath: '/chain-of-custody'
      preLoaderRoute: typeof AuthenticatedChainOfCustodyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scheduler/': {
      id: '/_authenticated/scheduler/'
      path: '/scheduler'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof AuthenticatedSchedulerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/': {
      id: '/_authenticated/samples/'
      path: '/samples'
      fullPath: '/samples/'
      preLoaderRoute: typeof AuthenticatedSamplesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run-lists/': {
      id: '/_authenticated/run-lists/'
      path: '/run-lists'
      fullPath: '/run-lists/'
      preLoaderRoute: typeof AuthenticatedRunListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/': {
      id: '/_authenticated/material-receipts/'
      path: '/material-receipts'
      fullPath: '/material-receipts/'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/': {
      id: '/_authenticated/lab-logs/'
      path: '/lab-logs'
      fullPath: '/lab-logs/'
      preLoaderRoute: typeof AuthenticatedLabLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-journal/': {
      id: '/_authenticated/lab-journal/'
      path: '/lab-journal'
      fullPath: '/lab-journal/'
      preLoaderRoute: typeof AuthenticatedLabJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/': {
      id: '/_authenticated/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthenticatedIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrument-comm/': {
      id: '/_authenticated/instrument-comm/'
      path: '/instrument-comm'
      fullPath: '/instrument-comm/'
      preLoaderRoute: typeof AuthenticatedInstrumentCommIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/new': {
      id: '/_authenticated/samples/new'
      path: '/samples/new'
      fullPath: '/samples/new'
      preLoaderRoute: typeof AuthenticatedSamplesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/$batchId': {
      id: '/_authenticated/samples/$batchId'
      path: '/samples/$batchId'
      fullPath: '/samples/$batchId'
      preLoaderRoute: typeof AuthenticatedSamplesBatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run-lists/$id': {
      id: '/_authenticated/run-lists/$id'
      path: '/run-lists/$id'
      fullPath: '/run-lists/$id'
      preLoaderRoute: typeof AuthenticatedRunListsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/new': {
      id: '/_authenticated/material-receipts/new'
      path: '/material-receipts/new'
      fullPath: '/material-receipts/new'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/accounting-report': {
      id: '/_authenticated/material-receipts/accounting-report'
      path: '/material-receipts/accounting-report'
      fullPath: '/material-receipts/accounting-report'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsAccountingReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/$id': {
      id: '/_authenticated/material-receipts/$id'
      path: '/material-receipts/$id'
      fullPath: '/material-receipts/$id'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrument-comm/openlab': {
      id: '/_authenticated/instrument-comm/openlab'
      path: '/instrument-comm/openlab'
      fullPath: '/instrument-comm/openlab'
      preLoaderRoute: typeof AuthenticatedInstrumentCommOpenlabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/timesheet-projects': {
      id: '/_authenticated/admin/timesheet-projects'
      path: '/admin/timesheet-projects'
      fullPath: '/admin/timesheet-projects'
      preLoaderRoute: typeof AuthenticatedAdminTimesheetProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/run-list-columns': {
      id: '/_authenticated/admin/run-list-columns'
      path: '/admin/run-list-columns'
      fullPath: '/admin/run-list-columns'
      preLoaderRoute: typeof AuthenticatedAdminRunListColumnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/parameters': {
      id: '/_authenticated/admin/parameters'
      path: '/admin/parameters'
      fullPath: '/admin/parameters'
      preLoaderRoute: typeof AuthenticatedAdminParametersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/mobile-phase-reagents': {
      id: '/_authenticated/admin/mobile-phase-reagents'
      path: '/admin/mobile-phase-reagents'
      fullPath: '/admin/mobile-phase-reagents'
      preLoaderRoute: typeof AuthenticatedAdminMobilePhaseReagentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/instruments': {
      id: '/_authenticated/admin/instruments'
      path: '/admin/instruments'
      fullPath: '/admin/instruments'
      preLoaderRoute: typeof AuthenticatedAdminInstrumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hplc-columns': {
      id: '/_authenticated/admin/hplc-columns'
      path: '/admin/hplc-columns'
      fullPath: '/admin/hplc-columns'
      preLoaderRoute: typeof AuthenticatedAdminHplcColumnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/compounds': {
      id: '/_authenticated/admin/compounds'
      path: '/admin/compounds'
      fullPath: '/admin/compounds'
      preLoaderRoute: typeof AuthenticatedAdminCompoundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/coc-fields': {
      id: '/_authenticated/admin/coc-fields'
      path: '/admin/coc-fields'
      fullPath: '/admin/coc-fields'
      preLoaderRoute: typeof AuthenticatedAdminCocFieldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access-logs': {
      id: '/_authenticated/admin/access-logs'
      path: '/admin/access-logs'
      fullPath: '/admin/access-logs'
      preLoaderRoute: typeof AuthenticatedAdminAccessLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/timesheets/': {
      id: '/_authenticated/lab-logs/timesheets/'
      path: '/lab-logs/timesheets'
      fullPath: '/lab-logs/timesheets/'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/': {
      id: '/_authenticated/lab-logs/standard-preparations/'
      path: '/lab-logs/standard-preparations'
      fullPath: '/lab-logs/standard-preparations/'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/parameter-scouting/': {
      id: '/_authenticated/lab-logs/parameter-scouting/'
      path: '/lab-logs/parameter-scouting'
      fullPath: '/lab-logs/parameter-scouting/'
      preLoaderRoute: typeof AuthenticatedLabLogsParameterScoutingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/mobile-phase/': {
      id: '/_authenticated/lab-logs/mobile-phase/'
      path: '/lab-logs/mobile-phase'
      fullPath: '/lab-logs/mobile-phase/'
      preLoaderRoute: typeof AuthenticatedLabLogsMobilePhaseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/daily-backpressure/': {
      id: '/_authenticated/lab-logs/daily-backpressure/'
      path: '/lab-logs/daily-backpressure'
      fullPath: '/lab-logs/daily-backpressure/'
      preLoaderRoute: typeof AuthenticatedLabLogsDailyBackpressureIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/exports/$batchId': {
      id: '/api/public/exports/$batchId'
      path: '/api/public/exports/$batchId'
      fullPath: '/api/public/exports/$batchId'
      preLoaderRoute: typeof ApiPublicExportsBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lab-logs/timesheets/reports': {
      id: '/_authenticated/lab-logs/timesheets/reports'
      path: '/lab-logs/timesheets/reports'
      fullPath: '/lab-logs/timesheets/reports'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/timesheets/history': {
      id: '/_authenticated/lab-logs/timesheets/history'
      path: '/lab-logs/timesheets/history'
      fullPath: '/lab-logs/timesheets/history'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/timesheets/daily': {
      id: '/_authenticated/lab-logs/timesheets/daily'
      path: '/lab-logs/timesheets/daily'
      fullPath: '/lab-logs/timesheets/daily'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsDailyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/new': {
      id: '/_authenticated/lab-logs/standard-preparations/new'
      path: '/lab-logs/standard-preparations/new'
      fullPath: '/lab-logs/standard-preparations/new'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/$id': {
      id: '/_authenticated/lab-logs/standard-preparations/$id'
      path: '/lab-logs/standard-preparations/$id'
      fullPath: '/lab-logs/standard-preparations/$id'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/mobile-phase/new': {
      id: '/_authenticated/lab-logs/mobile-phase/new'
      path: '/lab-logs/mobile-phase/new'
      fullPath: '/lab-logs/mobile-phase/new'
      preLoaderRoute: typeof AuthenticatedLabLogsMobilePhaseNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/mobile-phase/$id': {
      id: '/_authenticated/lab-logs/mobile-phase/$id'
      path: '/lab-logs/mobile-phase/$id'
      fullPath: '/lab-logs/mobile-phase/$id'
      preLoaderRoute: typeof AuthenticatedLabLogsMobilePhaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/batch/$groupId': {
      id: '/_authenticated/lab-logs/standard-preparations/batch/$groupId'
      path: '/lab-logs/standard-preparations/batch/$groupId'
      fullPath: '/lab-logs/standard-preparations/batch/$groupId'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChainOfCustodyRoute: typeof AuthenticatedChainOfCustodyRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAccessLogsRoute: typeof AuthenticatedAdminAccessLogsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminCocFieldsRoute: typeof AuthenticatedAdminCocFieldsRoute
  AuthenticatedAdminCompoundsRoute: typeof AuthenticatedAdminCompoundsRoute
  AuthenticatedAdminHplcColumnsRoute: typeof AuthenticatedAdminHplcColumnsRoute
  AuthenticatedAdminInstrumentsRoute: typeof AuthenticatedAdminInstrumentsRoute
  AuthenticatedAdminMobilePhaseReagentsRoute: typeof AuthenticatedAdminMobilePhaseReagentsRoute
  AuthenticatedAdminParametersRoute: typeof AuthenticatedAdminParametersRoute
  AuthenticatedAdminRunListColumnsRoute: typeof AuthenticatedAdminRunListColumnsRoute
  AuthenticatedAdminTimesheetProjectsRoute: typeof AuthenticatedAdminTimesheetProjectsRoute
  AuthenticatedInstrumentCommOpenlabRoute: typeof AuthenticatedInstrumentCommOpenlabRoute
  AuthenticatedMaterialReceiptsIdRoute: typeof AuthenticatedMaterialReceiptsIdRoute
  AuthenticatedMaterialReceiptsAccountingReportRoute: typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  AuthenticatedMaterialReceiptsNewRoute: typeof AuthenticatedMaterialReceiptsNewRoute
  AuthenticatedRunListsIdRoute: typeof AuthenticatedRunListsIdRoute
  AuthenticatedSamplesBatchIdRoute: typeof AuthenticatedSamplesBatchIdRoute
  AuthenticatedSamplesNewRoute: typeof AuthenticatedSamplesNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedInstrumentCommIndexRoute: typeof AuthenticatedInstrumentCommIndexRoute
  AuthenticatedIssuesIndexRoute: typeof AuthenticatedIssuesIndexRoute
  AuthenticatedLabJournalIndexRoute: typeof AuthenticatedLabJournalIndexRoute
  AuthenticatedLabLogsIndexRoute: typeof AuthenticatedLabLogsIndexRoute
  AuthenticatedMaterialReceiptsIndexRoute: typeof AuthenticatedMaterialReceiptsIndexRoute
  AuthenticatedRunListsIndexRoute: typeof AuthenticatedRunListsIndexRoute
  AuthenticatedSamplesIndexRoute: typeof AuthenticatedSamplesIndexRoute
  AuthenticatedSchedulerIndexRoute: typeof AuthenticatedSchedulerIndexRoute
  AuthenticatedLabLogsMobilePhaseIdRoute: typeof AuthenticatedLabLogsMobilePhaseIdRoute
  AuthenticatedLabLogsMobilePhaseNewRoute: typeof AuthenticatedLabLogsMobilePhaseNewRoute
  AuthenticatedLabLogsStandardPreparationsIdRoute: typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  AuthenticatedLabLogsStandardPreparationsNewRoute: typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  AuthenticatedLabLogsTimesheetsDailyRoute: typeof AuthenticatedLabLogsTimesheetsDailyRoute
  AuthenticatedLabLogsTimesheetsHistoryRoute: typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  AuthenticatedLabLogsTimesheetsReportsRoute: typeof AuthenticatedLabLogsTimesheetsReportsRoute
  AuthenticatedLabLogsDailyBackpressureIndexRoute: typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  AuthenticatedLabLogsMobilePhaseIndexRoute: typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  AuthenticatedLabLogsParameterScoutingIndexRoute: typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  AuthenticatedLabLogsStandardPreparationsIndexRoute: typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  AuthenticatedLabLogsTimesheetsIndexRoute: typeof AuthenticatedLabLogsTimesheetsIndexRoute
  AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute: typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChainOfCustodyRoute: AuthenticatedChainOfCustodyRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAccessLogsRoute: AuthenticatedAdminAccessLogsRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminCocFieldsRoute: AuthenticatedAdminCocFieldsRoute,
  AuthenticatedAdminCompoundsRoute: AuthenticatedAdminCompoundsRoute,
  AuthenticatedAdminHplcColumnsRoute: AuthenticatedAdminHplcColumnsRoute,
  AuthenticatedAdminInstrumentsRoute: AuthenticatedAdminInstrumentsRoute,
  AuthenticatedAdminMobilePhaseReagentsRoute:
    AuthenticatedAdminMobilePhaseReagentsRoute,
  AuthenticatedAdminParametersRoute: AuthenticatedAdminParametersRoute,
  AuthenticatedAdminRunListColumnsRoute: AuthenticatedAdminRunListColumnsRoute,
  AuthenticatedAdminTimesheetProjectsRoute:
    AuthenticatedAdminTimesheetProjectsRoute,
  AuthenticatedInstrumentCommOpenlabRoute:
    AuthenticatedInstrumentCommOpenlabRoute,
  AuthenticatedMaterialReceiptsIdRoute: AuthenticatedMaterialReceiptsIdRoute,
  AuthenticatedMaterialReceiptsAccountingReportRoute:
    AuthenticatedMaterialReceiptsAccountingReportRoute,
  AuthenticatedMaterialReceiptsNewRoute: AuthenticatedMaterialReceiptsNewRoute,
  AuthenticatedRunListsIdRoute: AuthenticatedRunListsIdRoute,
  AuthenticatedSamplesBatchIdRoute: AuthenticatedSamplesBatchIdRoute,
  AuthenticatedSamplesNewRoute: AuthenticatedSamplesNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedInstrumentCommIndexRoute: AuthenticatedInstrumentCommIndexRoute,
  AuthenticatedIssuesIndexRoute: AuthenticatedIssuesIndexRoute,
  AuthenticatedLabJournalIndexRoute: AuthenticatedLabJournalIndexRoute,
  AuthenticatedLabLogsIndexRoute: AuthenticatedLabLogsIndexRoute,
  AuthenticatedMaterialReceiptsIndexRoute:
    AuthenticatedMaterialReceiptsIndexRoute,
  AuthenticatedRunListsIndexRoute: AuthenticatedRunListsIndexRoute,
  AuthenticatedSamplesIndexRoute: AuthenticatedSamplesIndexRoute,
  AuthenticatedSchedulerIndexRoute: AuthenticatedSchedulerIndexRoute,
  AuthenticatedLabLogsMobilePhaseIdRoute:
    AuthenticatedLabLogsMobilePhaseIdRoute,
  AuthenticatedLabLogsMobilePhaseNewRoute:
    AuthenticatedLabLogsMobilePhaseNewRoute,
  AuthenticatedLabLogsStandardPreparationsIdRoute:
    AuthenticatedLabLogsStandardPreparationsIdRoute,
  AuthenticatedLabLogsStandardPreparationsNewRoute:
    AuthenticatedLabLogsStandardPreparationsNewRoute,
  AuthenticatedLabLogsTimesheetsDailyRoute:
    AuthenticatedLabLogsTimesheetsDailyRoute,
  AuthenticatedLabLogsTimesheetsHistoryRoute:
    AuthenticatedLabLogsTimesheetsHistoryRoute,
  AuthenticatedLabLogsTimesheetsReportsRoute:
    AuthenticatedLabLogsTimesheetsReportsRoute,
  AuthenticatedLabLogsDailyBackpressureIndexRoute:
    AuthenticatedLabLogsDailyBackpressureIndexRoute,
  AuthenticatedLabLogsMobilePhaseIndexRoute:
    AuthenticatedLabLogsMobilePhaseIndexRoute,
  AuthenticatedLabLogsParameterScoutingIndexRoute:
    AuthenticatedLabLogsParameterScoutingIndexRoute,
  AuthenticatedLabLogsStandardPreparationsIndexRoute:
    AuthenticatedLabLogsStandardPreparationsIndexRoute,
  AuthenticatedLabLogsTimesheetsIndexRoute:
    AuthenticatedLabLogsTimesheetsIndexRoute,
  AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute:
    AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicExportsBatchIdRoute: ApiPublicExportsBatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
