/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatTroubleshootingRouteImport } from './routes/api/chat-troubleshooting'
import { Route as ApiChatColumnAdvisorRouteImport } from './routes/api/chat-column-advisor'
import { Route as AuthenticatedVialLabelsRouteImport } from './routes/_authenticated/vial-labels'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedChainOfCustodyRouteImport } from './routes/_authenticated/chain-of-custody'
import { Route as AuthenticatedSchedulerIndexRouteImport } from './routes/_authenticated/scheduler/index'
import { Route as AuthenticatedSamplesIndexRouteImport } from './routes/_authenticated/samples/index'
import { Route as AuthenticatedSamplePrepIndexRouteImport } from './routes/_authenticated/sample-prep/index'
import { Route as AuthenticatedRunListsIndexRouteImport } from './routes/_authenticated/run-lists/index'
import { Route as AuthenticatedQueueIndexRouteImport } from './routes/_authenticated/queue/index'
import { Route as AuthenticatedPendingOrdersIndexRouteImport } from './routes/_authenticated/pending-orders/index'
import { Route as AuthenticatedMaterialReceiptsIndexRouteImport } from './routes/_authenticated/material-receipts/index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance/index'
import { Route as AuthenticatedLabLogsIndexRouteImport } from './routes/_authenticated/lab-logs/index'
import { Route as AuthenticatedLabJournalIndexRouteImport } from './routes/_authenticated/lab-journal/index'
import { Route as AuthenticatedIssuesIndexRouteImport } from './routes/_authenticated/issues/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedInstrumentCommIndexRouteImport } from './routes/_authenticated/instrument-comm/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSamplesNewRouteImport } from './routes/_authenticated/samples/new'
import { Route as AuthenticatedSamplesBatchIdRouteImport } from './routes/_authenticated/samples/$batchId'
import { Route as AuthenticatedSamplePrepVesselsRouteImport } from './routes/_authenticated/sample-prep/vessels'
import { Route as AuthenticatedSamplePrepSolventsRouteImport } from './routes/_authenticated/sample-prep/solvents'
import { Route as AuthenticatedSamplePrepQuickDilutionRouteImport } from './routes/_authenticated/sample-prep/quick-dilution'
import { Route as AuthenticatedSamplePrepMethodsRouteImport } from './routes/_authenticated/sample-prep/methods'
import { Route as AuthenticatedSamplePrepEquipmentRouteImport } from './routes/_authenticated/sample-prep/equipment'
import { Route as AuthenticatedSamplePrepAnalytesRouteImport } from './routes/_authenticated/sample-prep/analytes'
import { Route as AuthenticatedRunListsGenerateRouteImport } from './routes/_authenticated/run-lists/generate'
import { Route as AuthenticatedRunListsIdRouteImport } from './routes/_authenticated/run-lists/$id'
import { Route as AuthenticatedMaterialReceiptsNewRouteImport } from './routes/_authenticated/material-receipts/new'
import { Route as AuthenticatedMaterialReceiptsAccountingReportRouteImport } from './routes/_authenticated/material-receipts/accounting-report'
import { Route as AuthenticatedMaterialReceiptsIdRouteImport } from './routes/_authenticated/material-receipts/$id'
import { Route as AuthenticatedMaintenanceTroubleshootingRouteImport } from './routes/_authenticated/maintenance/troubleshooting'
import { Route as AuthenticatedMaintenancePartPickerRouteImport } from './routes/_authenticated/maintenance/part-picker'
import { Route as AuthenticatedMaintenanceKnowledgeBaseRouteImport } from './routes/_authenticated/maintenance/knowledge-base'
import { Route as AuthenticatedMaintenanceHplcColumnsRouteImport } from './routes/_authenticated/maintenance/hplc-columns'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory/new'
import { Route as AuthenticatedInventoryInstrumentsRouteImport } from './routes/_authenticated/inventory/instruments'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory/$id'
import { Route as AuthenticatedInstrumentCommOpenlabRouteImport } from './routes/_authenticated/instrument-comm/openlab'
import { Route as AuthenticatedAdminTraysRouteImport } from './routes/_authenticated/admin/trays'
import { Route as AuthenticatedAdminTimesheetProjectsRouteImport } from './routes/_authenticated/admin/timesheet-projects'
import { Route as AuthenticatedAdminRunListColumnsRouteImport } from './routes/_authenticated/admin/run-list-columns'
import { Route as AuthenticatedAdminQueueConfigRouteImport } from './routes/_authenticated/admin/queue-config'
import { Route as AuthenticatedAdminPartnerWebhookSecretRouteImport } from './routes/_authenticated/admin/partner-webhook-secret'
import { Route as AuthenticatedAdminParametersRouteImport } from './routes/_authenticated/admin/parameters'
import { Route as AuthenticatedAdminMobilePhaseReagentsRouteImport } from './routes/_authenticated/admin/mobile-phase-reagents'
import { Route as AuthenticatedAdminMethodGroupsRouteImport } from './routes/_authenticated/admin/method-groups'
import { Route as AuthenticatedAdminInstrumentsRouteImport } from './routes/_authenticated/admin/instruments'
import { Route as AuthenticatedAdminHplcColumnsRouteImport } from './routes/_authenticated/admin/hplc-columns'
import { Route as AuthenticatedAdminCompoundsRouteImport } from './routes/_authenticated/admin/compounds'
import { Route as AuthenticatedAdminCocFieldsRouteImport } from './routes/_authenticated/admin/coc-fields'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminAccessLogsRouteImport } from './routes/_authenticated/admin/access-logs'
import { Route as ApiPublicStatusIndexRouteImport } from './routes/api/public/status/index'
import { Route as AuthenticatedLabLogsTimesheetsIndexRouteImport } from './routes/_authenticated/lab-logs/timesheets/index'
import { Route as AuthenticatedLabLogsStandardPreparationsIndexRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/index'
import { Route as AuthenticatedLabLogsParameterScoutingIndexRouteImport } from './routes/_authenticated/lab-logs/parameter-scouting/index'
import { Route as AuthenticatedLabLogsMobilePhaseIndexRouteImport } from './routes/_authenticated/lab-logs/mobile-phase/index'
import { Route as AuthenticatedLabLogsDailyBackpressureIndexRouteImport } from './routes/_authenticated/lab-logs/daily-backpressure/index'
import { Route as ApiPublicStatusBatchIdRouteImport } from './routes/api/public/status/$batchId'
import { Route as ApiPublicOrdersIntakeRouteImport } from './routes/api/public/orders/intake'
import { Route as ApiPublicExportsBatchIdRouteImport } from './routes/api/public/exports/$batchId'
import { Route as ApiPublicColumnsDataVendorRouteImport } from './routes/api/public/columns-data/$vendor'
import { Route as AuthenticatedLabLogsTimesheetsReportsRouteImport } from './routes/_authenticated/lab-logs/timesheets/reports'
import { Route as AuthenticatedLabLogsTimesheetsHistoryRouteImport } from './routes/_authenticated/lab-logs/timesheets/history'
import { Route as AuthenticatedLabLogsTimesheetsDailyRouteImport } from './routes/_authenticated/lab-logs/timesheets/daily'
import { Route as AuthenticatedLabLogsStandardPreparationsNewRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/new'
import { Route as AuthenticatedLabLogsStandardPreparationsIdRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/$id'
import { Route as AuthenticatedLabLogsMobilePhaseNewRouteImport } from './routes/_authenticated/lab-logs/mobile-phase/new'
import { Route as AuthenticatedLabLogsMobilePhaseIdRouteImport } from './routes/_authenticated/lab-logs/mobile-phase/$id'
import { Route as AuthenticatedLabLogsStandardPreparationsBatchGroupIdRouteImport } from './routes/_authenticated/lab-logs/standard-preparations/batch.$groupId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatTroubleshootingRoute = ApiChatTroubleshootingRouteImport.update({
  id: '/api/chat-troubleshooting',
  path: '/api/chat-troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatColumnAdvisorRoute = ApiChatColumnAdvisorRouteImport.update({
  id: '/api/chat-column-advisor',
  path: '/api/chat-column-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVialLabelsRoute = AuthenticatedVialLabelsRouteImport.update({
  id: '/vial-labels',
  path: '/vial-labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChainOfCustodyRoute =
  AuthenticatedChainOfCustodyRouteImport.update({
    id: '/chain-of-custody',
    path: '/chain-of-custody',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchedulerIndexRoute =
  AuthenticatedSchedulerIndexRouteImport.update({
    id: '/scheduler/',
    path: '/scheduler/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesIndexRoute =
  AuthenticatedSamplesIndexRouteImport.update({
    id: '/samples/',
    path: '/samples/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepIndexRoute =
  AuthenticatedSamplePrepIndexRouteImport.update({
    id: '/sample-prep/',
    path: '/sample-prep/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunListsIndexRoute =
  AuthenticatedRunListsIndexRouteImport.update({
    id: '/run-lists/',
    path: '/run-lists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueueIndexRoute = AuthenticatedQueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingOrdersIndexRoute =
  AuthenticatedPendingOrdersIndexRouteImport.update({
    id: '/pending-orders/',
    path: '/pending-orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialReceiptsIndexRoute =
  AuthenticatedMaterialReceiptsIndexRouteImport.update({
    id: '/material-receipts/',
    path: '/material-receipts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsIndexRoute =
  AuthenticatedLabLogsIndexRouteImport.update({
    id: '/lab-logs/',
    path: '/lab-logs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabJournalIndexRoute =
  AuthenticatedLabJournalIndexRouteImport.update({
    id: '/lab-journal/',
    path: '/lab-journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIndexRoute =
  AuthenticatedIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrumentCommIndexRoute =
  AuthenticatedInstrumentCommIndexRouteImport.update({
    id: '/instrument-comm/',
    path: '/instrument-comm/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesNewRoute = AuthenticatedSamplesNewRouteImport.update({
  id: '/samples/new',
  path: '/samples/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesBatchIdRoute =
  AuthenticatedSamplesBatchIdRouteImport.update({
    id: '/samples/$batchId',
    path: '/samples/$batchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepVesselsRoute =
  AuthenticatedSamplePrepVesselsRouteImport.update({
    id: '/sample-prep/vessels',
    path: '/sample-prep/vessels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepSolventsRoute =
  AuthenticatedSamplePrepSolventsRouteImport.update({
    id: '/sample-prep/solvents',
    path: '/sample-prep/solvents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepQuickDilutionRoute =
  AuthenticatedSamplePrepQuickDilutionRouteImport.update({
    id: '/sample-prep/quick-dilution',
    path: '/sample-prep/quick-dilution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepMethodsRoute =
  AuthenticatedSamplePrepMethodsRouteImport.update({
    id: '/sample-prep/methods',
    path: '/sample-prep/methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepEquipmentRoute =
  AuthenticatedSamplePrepEquipmentRouteImport.update({
    id: '/sample-prep/equipment',
    path: '/sample-prep/equipment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplePrepAnalytesRoute =
  AuthenticatedSamplePrepAnalytesRouteImport.update({
    id: '/sample-prep/analytes',
    path: '/sample-prep/analytes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunListsGenerateRoute =
  AuthenticatedRunListsGenerateRouteImport.update({
    id: '/run-lists/generate',
    path: '/run-lists/generate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunListsIdRoute = AuthenticatedRunListsIdRouteImport.update({
  id: '/run-lists/$id',
  path: '/run-lists/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialReceiptsNewRoute =
  AuthenticatedMaterialReceiptsNewRouteImport.update({
    id: '/material-receipts/new',
    path: '/material-receipts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialReceiptsAccountingReportRoute =
  AuthenticatedMaterialReceiptsAccountingReportRouteImport.update({
    id: '/material-receipts/accounting-report',
    path: '/material-receipts/accounting-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaterialReceiptsIdRoute =
  AuthenticatedMaterialReceiptsIdRouteImport.update({
    id: '/material-receipts/$id',
    path: '/material-receipts/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceTroubleshootingRoute =
  AuthenticatedMaintenanceTroubleshootingRouteImport.update({
    id: '/maintenance/troubleshooting',
    path: '/maintenance/troubleshooting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenancePartPickerRoute =
  AuthenticatedMaintenancePartPickerRouteImport.update({
    id: '/maintenance/part-picker',
    path: '/maintenance/part-picker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceKnowledgeBaseRoute =
  AuthenticatedMaintenanceKnowledgeBaseRouteImport.update({
    id: '/maintenance/knowledge-base',
    path: '/maintenance/knowledge-base',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceHplcColumnsRoute =
  AuthenticatedMaintenanceHplcColumnsRouteImport.update({
    id: '/maintenance/hplc-columns',
    path: '/maintenance/hplc-columns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryInstrumentsRoute =
  AuthenticatedInventoryInstrumentsRouteImport.update({
    id: '/inventory/instruments',
    path: '/inventory/instruments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrumentCommOpenlabRoute =
  AuthenticatedInstrumentCommOpenlabRouteImport.update({
    id: '/instrument-comm/openlab',
    path: '/instrument-comm/openlab',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTraysRoute = AuthenticatedAdminTraysRouteImport.update({
  id: '/admin/trays',
  path: '/admin/trays',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTimesheetProjectsRoute =
  AuthenticatedAdminTimesheetProjectsRouteImport.update({
    id: '/admin/timesheet-projects',
    path: '/admin/timesheet-projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRunListColumnsRoute =
  AuthenticatedAdminRunListColumnsRouteImport.update({
    id: '/admin/run-list-columns',
    path: '/admin/run-list-columns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQueueConfigRoute =
  AuthenticatedAdminQueueConfigRouteImport.update({
    id: '/admin/queue-config',
    path: '/admin/queue-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPartnerWebhookSecretRoute =
  AuthenticatedAdminPartnerWebhookSecretRouteImport.update({
    id: '/admin/partner-webhook-secret',
    path: '/admin/partner-webhook-secret',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminParametersRoute =
  AuthenticatedAdminParametersRouteImport.update({
    id: '/admin/parameters',
    path: '/admin/parameters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMobilePhaseReagentsRoute =
  AuthenticatedAdminMobilePhaseReagentsRouteImport.update({
    id: '/admin/mobile-phase-reagents',
    path: '/admin/mobile-phase-reagents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMethodGroupsRoute =
  AuthenticatedAdminMethodGroupsRouteImport.update({
    id: '/admin/method-groups',
    path: '/admin/method-groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInstrumentsRoute =
  AuthenticatedAdminInstrumentsRouteImport.update({
    id: '/admin/instruments',
    path: '/admin/instruments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHplcColumnsRoute =
  AuthenticatedAdminHplcColumnsRouteImport.update({
    id: '/admin/hplc-columns',
    path: '/admin/hplc-columns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCompoundsRoute =
  AuthenticatedAdminCompoundsRouteImport.update({
    id: '/admin/compounds',
    path: '/admin/compounds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCocFieldsRoute =
  AuthenticatedAdminCocFieldsRouteImport.update({
    id: '/admin/coc-fields',
    path: '/admin/coc-fields',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAccessLogsRoute =
  AuthenticatedAdminAccessLogsRouteImport.update({
    id: '/admin/access-logs',
    path: '/admin/access-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicStatusIndexRoute = ApiPublicStatusIndexRouteImport.update({
  id: '/api/public/status/',
  path: '/api/public/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLabLogsTimesheetsIndexRoute =
  AuthenticatedLabLogsTimesheetsIndexRouteImport.update({
    id: '/lab-logs/timesheets/',
    path: '/lab-logs/timesheets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsIndexRoute =
  AuthenticatedLabLogsStandardPreparationsIndexRouteImport.update({
    id: '/lab-logs/standard-preparations/',
    path: '/lab-logs/standard-preparations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsParameterScoutingIndexRoute =
  AuthenticatedLabLogsParameterScoutingIndexRouteImport.update({
    id: '/lab-logs/parameter-scouting/',
    path: '/lab-logs/parameter-scouting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsMobilePhaseIndexRoute =
  AuthenticatedLabLogsMobilePhaseIndexRouteImport.update({
    id: '/lab-logs/mobile-phase/',
    path: '/lab-logs/mobile-phase/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsDailyBackpressureIndexRoute =
  AuthenticatedLabLogsDailyBackpressureIndexRouteImport.update({
    id: '/lab-logs/daily-backpressure/',
    path: '/lab-logs/daily-backpressure/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicStatusBatchIdRoute = ApiPublicStatusBatchIdRouteImport.update({
  id: '/api/public/status/$batchId',
  path: '/api/public/status/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersIntakeRoute = ApiPublicOrdersIntakeRouteImport.update({
  id: '/api/public/orders/intake',
  path: '/api/public/orders/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportsBatchIdRoute = ApiPublicExportsBatchIdRouteImport.update({
  id: '/api/public/exports/$batchId',
  path: '/api/public/exports/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicColumnsDataVendorRoute =
  ApiPublicColumnsDataVendorRouteImport.update({
    id: '/api/public/columns-data/$vendor',
    path: '/api/public/columns-data/$vendor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLabLogsTimesheetsReportsRoute =
  AuthenticatedLabLogsTimesheetsReportsRouteImport.update({
    id: '/lab-logs/timesheets/reports',
    path: '/lab-logs/timesheets/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsTimesheetsHistoryRoute =
  AuthenticatedLabLogsTimesheetsHistoryRouteImport.update({
    id: '/lab-logs/timesheets/history',
    path: '/lab-logs/timesheets/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsTimesheetsDailyRoute =
  AuthenticatedLabLogsTimesheetsDailyRouteImport.update({
    id: '/lab-logs/timesheets/daily',
    path: '/lab-logs/timesheets/daily',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsNewRoute =
  AuthenticatedLabLogsStandardPreparationsNewRouteImport.update({
    id: '/lab-logs/standard-preparations/new',
    path: '/lab-logs/standard-preparations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsIdRoute =
  AuthenticatedLabLogsStandardPreparationsIdRouteImport.update({
    id: '/lab-logs/standard-preparations/$id',
    path: '/lab-logs/standard-preparations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsMobilePhaseNewRoute =
  AuthenticatedLabLogsMobilePhaseNewRouteImport.update({
    id: '/lab-logs/mobile-phase/new',
    path: '/lab-logs/mobile-phase/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsMobilePhaseIdRoute =
  AuthenticatedLabLogsMobilePhaseIdRouteImport.update({
    id: '/lab-logs/mobile-phase/$id',
    path: '/lab-logs/mobile-phase/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute =
  AuthenticatedLabLogsStandardPreparationsBatchGroupIdRouteImport.update({
    id: '/lab-logs/standard-preparations/batch/$groupId',
    path: '/lab-logs/standard-preparations/batch/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chain-of-custody': typeof AuthenticatedChainOfCustodyRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vial-labels': typeof AuthenticatedVialLabelsRoute
  '/api/chat-column-advisor': typeof ApiChatColumnAdvisorRoute
  '/api/chat-troubleshooting': typeof ApiChatTroubleshootingRoute
  '/admin/access-logs': typeof AuthenticatedAdminAccessLogsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/coc-fields': typeof AuthenticatedAdminCocFieldsRoute
  '/admin/compounds': typeof AuthenticatedAdminCompoundsRoute
  '/admin/hplc-columns': typeof AuthenticatedAdminHplcColumnsRoute
  '/admin/instruments': typeof AuthenticatedAdminInstrumentsRoute
  '/admin/method-groups': typeof AuthenticatedAdminMethodGroupsRoute
  '/admin/mobile-phase-reagents': typeof AuthenticatedAdminMobilePhaseReagentsRoute
  '/admin/parameters': typeof AuthenticatedAdminParametersRoute
  '/admin/partner-webhook-secret': typeof AuthenticatedAdminPartnerWebhookSecretRoute
  '/admin/queue-config': typeof AuthenticatedAdminQueueConfigRoute
  '/admin/run-list-columns': typeof AuthenticatedAdminRunListColumnsRoute
  '/admin/timesheet-projects': typeof AuthenticatedAdminTimesheetProjectsRoute
  '/admin/trays': typeof AuthenticatedAdminTraysRoute
  '/instrument-comm/openlab': typeof AuthenticatedInstrumentCommOpenlabRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/instruments': typeof AuthenticatedInventoryInstrumentsRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/maintenance/hplc-columns': typeof AuthenticatedMaintenanceHplcColumnsRoute
  '/maintenance/knowledge-base': typeof AuthenticatedMaintenanceKnowledgeBaseRoute
  '/maintenance/part-picker': typeof AuthenticatedMaintenancePartPickerRoute
  '/maintenance/troubleshooting': typeof AuthenticatedMaintenanceTroubleshootingRoute
  '/material-receipts/$id': typeof AuthenticatedMaterialReceiptsIdRoute
  '/material-receipts/accounting-report': typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  '/material-receipts/new': typeof AuthenticatedMaterialReceiptsNewRoute
  '/run-lists/$id': typeof AuthenticatedRunListsIdRoute
  '/run-lists/generate': typeof AuthenticatedRunListsGenerateRoute
  '/sample-prep/analytes': typeof AuthenticatedSamplePrepAnalytesRoute
  '/sample-prep/equipment': typeof AuthenticatedSamplePrepEquipmentRoute
  '/sample-prep/methods': typeof AuthenticatedSamplePrepMethodsRoute
  '/sample-prep/quick-dilution': typeof AuthenticatedSamplePrepQuickDilutionRoute
  '/sample-prep/solvents': typeof AuthenticatedSamplePrepSolventsRoute
  '/sample-prep/vessels': typeof AuthenticatedSamplePrepVesselsRoute
  '/samples/$batchId': typeof AuthenticatedSamplesBatchIdRoute
  '/samples/new': typeof AuthenticatedSamplesNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/instrument-comm/': typeof AuthenticatedInstrumentCommIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/issues/': typeof AuthenticatedIssuesIndexRoute
  '/lab-journal/': typeof AuthenticatedLabJournalIndexRoute
  '/lab-logs/': typeof AuthenticatedLabLogsIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/material-receipts/': typeof AuthenticatedMaterialReceiptsIndexRoute
  '/pending-orders/': typeof AuthenticatedPendingOrdersIndexRoute
  '/queue/': typeof AuthenticatedQueueIndexRoute
  '/run-lists/': typeof AuthenticatedRunListsIndexRoute
  '/sample-prep/': typeof AuthenticatedSamplePrepIndexRoute
  '/samples/': typeof AuthenticatedSamplesIndexRoute
  '/scheduler/': typeof AuthenticatedSchedulerIndexRoute
  '/lab-logs/mobile-phase/$id': typeof AuthenticatedLabLogsMobilePhaseIdRoute
  '/lab-logs/mobile-phase/new': typeof AuthenticatedLabLogsMobilePhaseNewRoute
  '/lab-logs/standard-preparations/$id': typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  '/lab-logs/standard-preparations/new': typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  '/lab-logs/timesheets/daily': typeof AuthenticatedLabLogsTimesheetsDailyRoute
  '/lab-logs/timesheets/history': typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  '/lab-logs/timesheets/reports': typeof AuthenticatedLabLogsTimesheetsReportsRoute
  '/api/public/columns-data/$vendor': typeof ApiPublicColumnsDataVendorRoute
  '/api/public/exports/$batchId': typeof ApiPublicExportsBatchIdRoute
  '/api/public/orders/intake': typeof ApiPublicOrdersIntakeRoute
  '/api/public/status/$batchId': typeof ApiPublicStatusBatchIdRoute
  '/lab-logs/daily-backpressure/': typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  '/lab-logs/mobile-phase/': typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  '/lab-logs/parameter-scouting/': typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  '/lab-logs/standard-preparations/': typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  '/lab-logs/timesheets/': typeof AuthenticatedLabLogsTimesheetsIndexRoute
  '/api/public/status/': typeof ApiPublicStatusIndexRoute
  '/lab-logs/standard-preparations/batch/$groupId': typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chain-of-custody': typeof AuthenticatedChainOfCustodyRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vial-labels': typeof AuthenticatedVialLabelsRoute
  '/api/chat-column-advisor': typeof ApiChatColumnAdvisorRoute
  '/api/chat-troubleshooting': typeof ApiChatTroubleshootingRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/access-logs': typeof AuthenticatedAdminAccessLogsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/coc-fields': typeof AuthenticatedAdminCocFieldsRoute
  '/admin/compounds': typeof AuthenticatedAdminCompoundsRoute
  '/admin/hplc-columns': typeof AuthenticatedAdminHplcColumnsRoute
  '/admin/instruments': typeof AuthenticatedAdminInstrumentsRoute
  '/admin/method-groups': typeof AuthenticatedAdminMethodGroupsRoute
  '/admin/mobile-phase-reagents': typeof AuthenticatedAdminMobilePhaseReagentsRoute
  '/admin/parameters': typeof AuthenticatedAdminParametersRoute
  '/admin/partner-webhook-secret': typeof AuthenticatedAdminPartnerWebhookSecretRoute
  '/admin/queue-config': typeof AuthenticatedAdminQueueConfigRoute
  '/admin/run-list-columns': typeof AuthenticatedAdminRunListColumnsRoute
  '/admin/timesheet-projects': typeof AuthenticatedAdminTimesheetProjectsRoute
  '/admin/trays': typeof AuthenticatedAdminTraysRoute
  '/instrument-comm/openlab': typeof AuthenticatedInstrumentCommOpenlabRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/instruments': typeof AuthenticatedInventoryInstrumentsRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/maintenance/hplc-columns': typeof AuthenticatedMaintenanceHplcColumnsRoute
  '/maintenance/knowledge-base': typeof AuthenticatedMaintenanceKnowledgeBaseRoute
  '/maintenance/part-picker': typeof AuthenticatedMaintenancePartPickerRoute
  '/maintenance/troubleshooting': typeof AuthenticatedMaintenanceTroubleshootingRoute
  '/material-receipts/$id': typeof AuthenticatedMaterialReceiptsIdRoute
  '/material-receipts/accounting-report': typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  '/material-receipts/new': typeof AuthenticatedMaterialReceiptsNewRoute
  '/run-lists/$id': typeof AuthenticatedRunListsIdRoute
  '/run-lists/generate': typeof AuthenticatedRunListsGenerateRoute
  '/sample-prep/analytes': typeof AuthenticatedSamplePrepAnalytesRoute
  '/sample-prep/equipment': typeof AuthenticatedSamplePrepEquipmentRoute
  '/sample-prep/methods': typeof AuthenticatedSamplePrepMethodsRoute
  '/sample-prep/quick-dilution': typeof AuthenticatedSamplePrepQuickDilutionRoute
  '/sample-prep/solvents': typeof AuthenticatedSamplePrepSolventsRoute
  '/sample-prep/vessels': typeof AuthenticatedSamplePrepVesselsRoute
  '/samples/$batchId': typeof AuthenticatedSamplesBatchIdRoute
  '/samples/new': typeof AuthenticatedSamplesNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/instrument-comm': typeof AuthenticatedInstrumentCommIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/issues': typeof AuthenticatedIssuesIndexRoute
  '/lab-journal': typeof AuthenticatedLabJournalIndexRoute
  '/lab-logs': typeof AuthenticatedLabLogsIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/material-receipts': typeof AuthenticatedMaterialReceiptsIndexRoute
  '/pending-orders': typeof AuthenticatedPendingOrdersIndexRoute
  '/queue': typeof AuthenticatedQueueIndexRoute
  '/run-lists': typeof AuthenticatedRunListsIndexRoute
  '/sample-prep': typeof AuthenticatedSamplePrepIndexRoute
  '/samples': typeof AuthenticatedSamplesIndexRoute
  '/scheduler': typeof AuthenticatedSchedulerIndexRoute
  '/lab-logs/mobile-phase/$id': typeof AuthenticatedLabLogsMobilePhaseIdRoute
  '/lab-logs/mobile-phase/new': typeof AuthenticatedLabLogsMobilePhaseNewRoute
  '/lab-logs/standard-preparations/$id': typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  '/lab-logs/standard-preparations/new': typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  '/lab-logs/timesheets/daily': typeof AuthenticatedLabLogsTimesheetsDailyRoute
  '/lab-logs/timesheets/history': typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  '/lab-logs/timesheets/reports': typeof AuthenticatedLabLogsTimesheetsReportsRoute
  '/api/public/columns-data/$vendor': typeof ApiPublicColumnsDataVendorRoute
  '/api/public/exports/$batchId': typeof ApiPublicExportsBatchIdRoute
  '/api/public/orders/intake': typeof ApiPublicOrdersIntakeRoute
  '/api/public/status/$batchId': typeof ApiPublicStatusBatchIdRoute
  '/lab-logs/daily-backpressure': typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  '/lab-logs/mobile-phase': typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  '/lab-logs/parameter-scouting': typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  '/lab-logs/standard-preparations': typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  '/lab-logs/timesheets': typeof AuthenticatedLabLogsTimesheetsIndexRoute
  '/api/public/status': typeof ApiPublicStatusIndexRoute
  '/lab-logs/standard-preparations/batch/$groupId': typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/chain-of-custody': typeof AuthenticatedChainOfCustodyRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vial-labels': typeof AuthenticatedVialLabelsRoute
  '/api/chat-column-advisor': typeof ApiChatColumnAdvisorRoute
  '/api/chat-troubleshooting': typeof ApiChatTroubleshootingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/access-logs': typeof AuthenticatedAdminAccessLogsRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/coc-fields': typeof AuthenticatedAdminCocFieldsRoute
  '/_authenticated/admin/compounds': typeof AuthenticatedAdminCompoundsRoute
  '/_authenticated/admin/hplc-columns': typeof AuthenticatedAdminHplcColumnsRoute
  '/_authenticated/admin/instruments': typeof AuthenticatedAdminInstrumentsRoute
  '/_authenticated/admin/method-groups': typeof AuthenticatedAdminMethodGroupsRoute
  '/_authenticated/admin/mobile-phase-reagents': typeof AuthenticatedAdminMobilePhaseReagentsRoute
  '/_authenticated/admin/parameters': typeof AuthenticatedAdminParametersRoute
  '/_authenticated/admin/partner-webhook-secret': typeof AuthenticatedAdminPartnerWebhookSecretRoute
  '/_authenticated/admin/queue-config': typeof AuthenticatedAdminQueueConfigRoute
  '/_authenticated/admin/run-list-columns': typeof AuthenticatedAdminRunListColumnsRoute
  '/_authenticated/admin/timesheet-projects': typeof AuthenticatedAdminTimesheetProjectsRoute
  '/_authenticated/admin/trays': typeof AuthenticatedAdminTraysRoute
  '/_authenticated/instrument-comm/openlab': typeof AuthenticatedInstrumentCommOpenlabRoute
  '/_authenticated/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/_authenticated/inventory/instruments': typeof AuthenticatedInventoryInstrumentsRoute
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/maintenance/hplc-columns': typeof AuthenticatedMaintenanceHplcColumnsRoute
  '/_authenticated/maintenance/knowledge-base': typeof AuthenticatedMaintenanceKnowledgeBaseRoute
  '/_authenticated/maintenance/part-picker': typeof AuthenticatedMaintenancePartPickerRoute
  '/_authenticated/maintenance/troubleshooting': typeof AuthenticatedMaintenanceTroubleshootingRoute
  '/_authenticated/material-receipts/$id': typeof AuthenticatedMaterialReceiptsIdRoute
  '/_authenticated/material-receipts/accounting-report': typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  '/_authenticated/material-receipts/new': typeof AuthenticatedMaterialReceiptsNewRoute
  '/_authenticated/run-lists/$id': typeof AuthenticatedRunListsIdRoute
  '/_authenticated/run-lists/generate': typeof AuthenticatedRunListsGenerateRoute
  '/_authenticated/sample-prep/analytes': typeof AuthenticatedSamplePrepAnalytesRoute
  '/_authenticated/sample-prep/equipment': typeof AuthenticatedSamplePrepEquipmentRoute
  '/_authenticated/sample-prep/methods': typeof AuthenticatedSamplePrepMethodsRoute
  '/_authenticated/sample-prep/quick-dilution': typeof AuthenticatedSamplePrepQuickDilutionRoute
  '/_authenticated/sample-prep/solvents': typeof AuthenticatedSamplePrepSolventsRoute
  '/_authenticated/sample-prep/vessels': typeof AuthenticatedSamplePrepVesselsRoute
  '/_authenticated/samples/$batchId': typeof AuthenticatedSamplesBatchIdRoute
  '/_authenticated/samples/new': typeof AuthenticatedSamplesNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/instrument-comm/': typeof AuthenticatedInstrumentCommIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/issues/': typeof AuthenticatedIssuesIndexRoute
  '/_authenticated/lab-journal/': typeof AuthenticatedLabJournalIndexRoute
  '/_authenticated/lab-logs/': typeof AuthenticatedLabLogsIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/material-receipts/': typeof AuthenticatedMaterialReceiptsIndexRoute
  '/_authenticated/pending-orders/': typeof AuthenticatedPendingOrdersIndexRoute
  '/_authenticated/queue/': typeof AuthenticatedQueueIndexRoute
  '/_authenticated/run-lists/': typeof AuthenticatedRunListsIndexRoute
  '/_authenticated/sample-prep/': typeof AuthenticatedSamplePrepIndexRoute
  '/_authenticated/samples/': typeof AuthenticatedSamplesIndexRoute
  '/_authenticated/scheduler/': typeof AuthenticatedSchedulerIndexRoute
  '/_authenticated/lab-logs/mobile-phase/$id': typeof AuthenticatedLabLogsMobilePhaseIdRoute
  '/_authenticated/lab-logs/mobile-phase/new': typeof AuthenticatedLabLogsMobilePhaseNewRoute
  '/_authenticated/lab-logs/standard-preparations/$id': typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  '/_authenticated/lab-logs/standard-preparations/new': typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  '/_authenticated/lab-logs/timesheets/daily': typeof AuthenticatedLabLogsTimesheetsDailyRoute
  '/_authenticated/lab-logs/timesheets/history': typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  '/_authenticated/lab-logs/timesheets/reports': typeof AuthenticatedLabLogsTimesheetsReportsRoute
  '/api/public/columns-data/$vendor': typeof ApiPublicColumnsDataVendorRoute
  '/api/public/exports/$batchId': typeof ApiPublicExportsBatchIdRoute
  '/api/public/orders/intake': typeof ApiPublicOrdersIntakeRoute
  '/api/public/status/$batchId': typeof ApiPublicStatusBatchIdRoute
  '/_authenticated/lab-logs/daily-backpressure/': typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  '/_authenticated/lab-logs/mobile-phase/': typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  '/_authenticated/lab-logs/parameter-scouting/': typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  '/_authenticated/lab-logs/standard-preparations/': typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  '/_authenticated/lab-logs/timesheets/': typeof AuthenticatedLabLogsTimesheetsIndexRoute
  '/api/public/status/': typeof ApiPublicStatusIndexRoute
  '/_authenticated/lab-logs/standard-preparations/batch/$groupId': typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/chain-of-custody'
    | '/intake'
    | '/integrations'
    | '/library'
    | '/users'
    | '/vial-labels'
    | '/api/chat-column-advisor'
    | '/api/chat-troubleshooting'
    | '/admin/access-logs'
    | '/admin/audit-log'
    | '/admin/coc-fields'
    | '/admin/compounds'
    | '/admin/hplc-columns'
    | '/admin/instruments'
    | '/admin/method-groups'
    | '/admin/mobile-phase-reagents'
    | '/admin/parameters'
    | '/admin/partner-webhook-secret'
    | '/admin/queue-config'
    | '/admin/run-list-columns'
    | '/admin/timesheet-projects'
    | '/admin/trays'
    | '/instrument-comm/openlab'
    | '/inventory/$id'
    | '/inventory/instruments'
    | '/inventory/new'
    | '/maintenance/hplc-columns'
    | '/maintenance/knowledge-base'
    | '/maintenance/part-picker'
    | '/maintenance/troubleshooting'
    | '/material-receipts/$id'
    | '/material-receipts/accounting-report'
    | '/material-receipts/new'
    | '/run-lists/$id'
    | '/run-lists/generate'
    | '/sample-prep/analytes'
    | '/sample-prep/equipment'
    | '/sample-prep/methods'
    | '/sample-prep/quick-dilution'
    | '/sample-prep/solvents'
    | '/sample-prep/vessels'
    | '/samples/$batchId'
    | '/samples/new'
    | '/admin/'
    | '/clients/'
    | '/instrument-comm/'
    | '/inventory/'
    | '/issues/'
    | '/lab-journal/'
    | '/lab-logs/'
    | '/maintenance/'
    | '/material-receipts/'
    | '/pending-orders/'
    | '/queue/'
    | '/run-lists/'
    | '/sample-prep/'
    | '/samples/'
    | '/scheduler/'
    | '/lab-logs/mobile-phase/$id'
    | '/lab-logs/mobile-phase/new'
    | '/lab-logs/standard-preparations/$id'
    | '/lab-logs/standard-preparations/new'
    | '/lab-logs/timesheets/daily'
    | '/lab-logs/timesheets/history'
    | '/lab-logs/timesheets/reports'
    | '/api/public/columns-data/$vendor'
    | '/api/public/exports/$batchId'
    | '/api/public/orders/intake'
    | '/api/public/status/$batchId'
    | '/lab-logs/daily-backpressure/'
    | '/lab-logs/mobile-phase/'
    | '/lab-logs/parameter-scouting/'
    | '/lab-logs/standard-preparations/'
    | '/lab-logs/timesheets/'
    | '/api/public/status/'
    | '/lab-logs/standard-preparations/batch/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/chain-of-custody'
    | '/intake'
    | '/integrations'
    | '/library'
    | '/users'
    | '/vial-labels'
    | '/api/chat-column-advisor'
    | '/api/chat-troubleshooting'
    | '/'
    | '/admin/access-logs'
    | '/admin/audit-log'
    | '/admin/coc-fields'
    | '/admin/compounds'
    | '/admin/hplc-columns'
    | '/admin/instruments'
    | '/admin/method-groups'
    | '/admin/mobile-phase-reagents'
    | '/admin/parameters'
    | '/admin/partner-webhook-secret'
    | '/admin/queue-config'
    | '/admin/run-list-columns'
    | '/admin/timesheet-projects'
    | '/admin/trays'
    | '/instrument-comm/openlab'
    | '/inventory/$id'
    | '/inventory/instruments'
    | '/inventory/new'
    | '/maintenance/hplc-columns'
    | '/maintenance/knowledge-base'
    | '/maintenance/part-picker'
    | '/maintenance/troubleshooting'
    | '/material-receipts/$id'
    | '/material-receipts/accounting-report'
    | '/material-receipts/new'
    | '/run-lists/$id'
    | '/run-lists/generate'
    | '/sample-prep/analytes'
    | '/sample-prep/equipment'
    | '/sample-prep/methods'
    | '/sample-prep/quick-dilution'
    | '/sample-prep/solvents'
    | '/sample-prep/vessels'
    | '/samples/$batchId'
    | '/samples/new'
    | '/admin'
    | '/clients'
    | '/instrument-comm'
    | '/inventory'
    | '/issues'
    | '/lab-journal'
    | '/lab-logs'
    | '/maintenance'
    | '/material-receipts'
    | '/pending-orders'
    | '/queue'
    | '/run-lists'
    | '/sample-prep'
    | '/samples'
    | '/scheduler'
    | '/lab-logs/mobile-phase/$id'
    | '/lab-logs/mobile-phase/new'
    | '/lab-logs/standard-preparations/$id'
    | '/lab-logs/standard-preparations/new'
    | '/lab-logs/timesheets/daily'
    | '/lab-logs/timesheets/history'
    | '/lab-logs/timesheets/reports'
    | '/api/public/columns-data/$vendor'
    | '/api/public/exports/$batchId'
    | '/api/public/orders/intake'
    | '/api/public/status/$batchId'
    | '/lab-logs/daily-backpressure'
    | '/lab-logs/mobile-phase'
    | '/lab-logs/parameter-scouting'
    | '/lab-logs/standard-preparations'
    | '/lab-logs/timesheets'
    | '/api/public/status'
    | '/lab-logs/standard-preparations/batch/$groupId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/chain-of-custody'
    | '/_authenticated/intake'
    | '/_authenticated/integrations'
    | '/_authenticated/library'
    | '/_authenticated/users'
    | '/_authenticated/vial-labels'
    | '/api/chat-column-advisor'
    | '/api/chat-troubleshooting'
    | '/_authenticated/'
    | '/_authenticated/admin/access-logs'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/coc-fields'
    | '/_authenticated/admin/compounds'
    | '/_authenticated/admin/hplc-columns'
    | '/_authenticated/admin/instruments'
    | '/_authenticated/admin/method-groups'
    | '/_authenticated/admin/mobile-phase-reagents'
    | '/_authenticated/admin/parameters'
    | '/_authenticated/admin/partner-webhook-secret'
    | '/_authenticated/admin/queue-config'
    | '/_authenticated/admin/run-list-columns'
    | '/_authenticated/admin/timesheet-projects'
    | '/_authenticated/admin/trays'
    | '/_authenticated/instrument-comm/openlab'
    | '/_authenticated/inventory/$id'
    | '/_authenticated/inventory/instruments'
    | '/_authenticated/inventory/new'
    | '/_authenticated/maintenance/hplc-columns'
    | '/_authenticated/maintenance/knowledge-base'
    | '/_authenticated/maintenance/part-picker'
    | '/_authenticated/maintenance/troubleshooting'
    | '/_authenticated/material-receipts/$id'
    | '/_authenticated/material-receipts/accounting-report'
    | '/_authenticated/material-receipts/new'
    | '/_authenticated/run-lists/$id'
    | '/_authenticated/run-lists/generate'
    | '/_authenticated/sample-prep/analytes'
    | '/_authenticated/sample-prep/equipment'
    | '/_authenticated/sample-prep/methods'
    | '/_authenticated/sample-prep/quick-dilution'
    | '/_authenticated/sample-prep/solvents'
    | '/_authenticated/sample-prep/vessels'
    | '/_authenticated/samples/$batchId'
    | '/_authenticated/samples/new'
    | '/_authenticated/admin/'
    | '/_authenticated/clients/'
    | '/_authenticated/instrument-comm/'
    | '/_authenticated/inventory/'
    | '/_authenticated/issues/'
    | '/_authenticated/lab-journal/'
    | '/_authenticated/lab-logs/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/material-receipts/'
    | '/_authenticated/pending-orders/'
    | '/_authenticated/queue/'
    | '/_authenticated/run-lists/'
    | '/_authenticated/sample-prep/'
    | '/_authenticated/samples/'
    | '/_authenticated/scheduler/'
    | '/_authenticated/lab-logs/mobile-phase/$id'
    | '/_authenticated/lab-logs/mobile-phase/new'
    | '/_authenticated/lab-logs/standard-preparations/$id'
    | '/_authenticated/lab-logs/standard-preparations/new'
    | '/_authenticated/lab-logs/timesheets/daily'
    | '/_authenticated/lab-logs/timesheets/history'
    | '/_authenticated/lab-logs/timesheets/reports'
    | '/api/public/columns-data/$vendor'
    | '/api/public/exports/$batchId'
    | '/api/public/orders/intake'
    | '/api/public/status/$batchId'
    | '/_authenticated/lab-logs/daily-backpressure/'
    | '/_authenticated/lab-logs/mobile-phase/'
    | '/_authenticated/lab-logs/parameter-scouting/'
    | '/_authenticated/lab-logs/standard-preparations/'
    | '/_authenticated/lab-logs/timesheets/'
    | '/api/public/status/'
    | '/_authenticated/lab-logs/standard-preparations/batch/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatColumnAdvisorRoute: typeof ApiChatColumnAdvisorRoute
  ApiChatTroubleshootingRoute: typeof ApiChatTroubleshootingRoute
  ApiPublicColumnsDataVendorRoute: typeof ApiPublicColumnsDataVendorRoute
  ApiPublicExportsBatchIdRoute: typeof ApiPublicExportsBatchIdRoute
  ApiPublicOrdersIntakeRoute: typeof ApiPublicOrdersIntakeRoute
  ApiPublicStatusBatchIdRoute: typeof ApiPublicStatusBatchIdRoute
  ApiPublicStatusIndexRoute: typeof ApiPublicStatusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat-troubleshooting': {
      id: '/api/chat-troubleshooting'
      path: '/api/chat-troubleshooting'
      fullPath: '/api/chat-troubleshooting'
      preLoaderRoute: typeof ApiChatTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-column-advisor': {
      id: '/api/chat-column-advisor'
      path: '/api/chat-column-advisor'
      fullPath: '/api/chat-column-advisor'
      preLoaderRoute: typeof ApiChatColumnAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vial-labels': {
      id: '/_authenticated/vial-labels'
      path: '/vial-labels'
      fullPath: '/vial-labels'
      preLoaderRoute: typeof AuthenticatedVialLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chain-of-custody': {
      id: '/_authenticated/chain-of-custody'
      path: '/chain-of-custody'
      fullPath: '/chain-of-custody'
      preLoaderRoute: typeof AuthenticatedChainOfCustodyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scheduler/': {
      id: '/_authenticated/scheduler/'
      path: '/scheduler'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof AuthenticatedSchedulerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/': {
      id: '/_authenticated/samples/'
      path: '/samples'
      fullPath: '/samples/'
      preLoaderRoute: typeof AuthenticatedSamplesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/': {
      id: '/_authenticated/sample-prep/'
      path: '/sample-prep'
      fullPath: '/sample-prep/'
      preLoaderRoute: typeof AuthenticatedSamplePrepIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run-lists/': {
      id: '/_authenticated/run-lists/'
      path: '/run-lists'
      fullPath: '/run-lists/'
      preLoaderRoute: typeof AuthenticatedRunListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue/': {
      id: '/_authenticated/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof AuthenticatedQueueIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending-orders/': {
      id: '/_authenticated/pending-orders/'
      path: '/pending-orders'
      fullPath: '/pending-orders/'
      preLoaderRoute: typeof AuthenticatedPendingOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/': {
      id: '/_authenticated/material-receipts/'
      path: '/material-receipts'
      fullPath: '/material-receipts/'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/': {
      id: '/_authenticated/lab-logs/'
      path: '/lab-logs'
      fullPath: '/lab-logs/'
      preLoaderRoute: typeof AuthenticatedLabLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-journal/': {
      id: '/_authenticated/lab-journal/'
      path: '/lab-journal'
      fullPath: '/lab-journal/'
      preLoaderRoute: typeof AuthenticatedLabJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/': {
      id: '/_authenticated/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthenticatedIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrument-comm/': {
      id: '/_authenticated/instrument-comm/'
      path: '/instrument-comm'
      fullPath: '/instrument-comm/'
      preLoaderRoute: typeof AuthenticatedInstrumentCommIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/new': {
      id: '/_authenticated/samples/new'
      path: '/samples/new'
      fullPath: '/samples/new'
      preLoaderRoute: typeof AuthenticatedSamplesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/$batchId': {
      id: '/_authenticated/samples/$batchId'
      path: '/samples/$batchId'
      fullPath: '/samples/$batchId'
      preLoaderRoute: typeof AuthenticatedSamplesBatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/vessels': {
      id: '/_authenticated/sample-prep/vessels'
      path: '/sample-prep/vessels'
      fullPath: '/sample-prep/vessels'
      preLoaderRoute: typeof AuthenticatedSamplePrepVesselsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/solvents': {
      id: '/_authenticated/sample-prep/solvents'
      path: '/sample-prep/solvents'
      fullPath: '/sample-prep/solvents'
      preLoaderRoute: typeof AuthenticatedSamplePrepSolventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/quick-dilution': {
      id: '/_authenticated/sample-prep/quick-dilution'
      path: '/sample-prep/quick-dilution'
      fullPath: '/sample-prep/quick-dilution'
      preLoaderRoute: typeof AuthenticatedSamplePrepQuickDilutionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/methods': {
      id: '/_authenticated/sample-prep/methods'
      path: '/sample-prep/methods'
      fullPath: '/sample-prep/methods'
      preLoaderRoute: typeof AuthenticatedSamplePrepMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/equipment': {
      id: '/_authenticated/sample-prep/equipment'
      path: '/sample-prep/equipment'
      fullPath: '/sample-prep/equipment'
      preLoaderRoute: typeof AuthenticatedSamplePrepEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-prep/analytes': {
      id: '/_authenticated/sample-prep/analytes'
      path: '/sample-prep/analytes'
      fullPath: '/sample-prep/analytes'
      preLoaderRoute: typeof AuthenticatedSamplePrepAnalytesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run-lists/generate': {
      id: '/_authenticated/run-lists/generate'
      path: '/run-lists/generate'
      fullPath: '/run-lists/generate'
      preLoaderRoute: typeof AuthenticatedRunListsGenerateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run-lists/$id': {
      id: '/_authenticated/run-lists/$id'
      path: '/run-lists/$id'
      fullPath: '/run-lists/$id'
      preLoaderRoute: typeof AuthenticatedRunListsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/new': {
      id: '/_authenticated/material-receipts/new'
      path: '/material-receipts/new'
      fullPath: '/material-receipts/new'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/accounting-report': {
      id: '/_authenticated/material-receipts/accounting-report'
      path: '/material-receipts/accounting-report'
      fullPath: '/material-receipts/accounting-report'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsAccountingReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-receipts/$id': {
      id: '/_authenticated/material-receipts/$id'
      path: '/material-receipts/$id'
      fullPath: '/material-receipts/$id'
      preLoaderRoute: typeof AuthenticatedMaterialReceiptsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/troubleshooting': {
      id: '/_authenticated/maintenance/troubleshooting'
      path: '/maintenance/troubleshooting'
      fullPath: '/maintenance/troubleshooting'
      preLoaderRoute: typeof AuthenticatedMaintenanceTroubleshootingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/part-picker': {
      id: '/_authenticated/maintenance/part-picker'
      path: '/maintenance/part-picker'
      fullPath: '/maintenance/part-picker'
      preLoaderRoute: typeof AuthenticatedMaintenancePartPickerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/knowledge-base': {
      id: '/_authenticated/maintenance/knowledge-base'
      path: '/maintenance/knowledge-base'
      fullPath: '/maintenance/knowledge-base'
      preLoaderRoute: typeof AuthenticatedMaintenanceKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/hplc-columns': {
      id: '/_authenticated/maintenance/hplc-columns'
      path: '/maintenance/hplc-columns'
      fullPath: '/maintenance/hplc-columns'
      preLoaderRoute: typeof AuthenticatedMaintenanceHplcColumnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/instruments': {
      id: '/_authenticated/inventory/instruments'
      path: '/inventory/instruments'
      fullPath: '/inventory/instruments'
      preLoaderRoute: typeof AuthenticatedInventoryInstrumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/$id': {
      id: '/_authenticated/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrument-comm/openlab': {
      id: '/_authenticated/instrument-comm/openlab'
      path: '/instrument-comm/openlab'
      fullPath: '/instrument-comm/openlab'
      preLoaderRoute: typeof AuthenticatedInstrumentCommOpenlabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/trays': {
      id: '/_authenticated/admin/trays'
      path: '/admin/trays'
      fullPath: '/admin/trays'
      preLoaderRoute: typeof AuthenticatedAdminTraysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/timesheet-projects': {
      id: '/_authenticated/admin/timesheet-projects'
      path: '/admin/timesheet-projects'
      fullPath: '/admin/timesheet-projects'
      preLoaderRoute: typeof AuthenticatedAdminTimesheetProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/run-list-columns': {
      id: '/_authenticated/admin/run-list-columns'
      path: '/admin/run-list-columns'
      fullPath: '/admin/run-list-columns'
      preLoaderRoute: typeof AuthenticatedAdminRunListColumnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/queue-config': {
      id: '/_authenticated/admin/queue-config'
      path: '/admin/queue-config'
      fullPath: '/admin/queue-config'
      preLoaderRoute: typeof AuthenticatedAdminQueueConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/partner-webhook-secret': {
      id: '/_authenticated/admin/partner-webhook-secret'
      path: '/admin/partner-webhook-secret'
      fullPath: '/admin/partner-webhook-secret'
      preLoaderRoute: typeof AuthenticatedAdminPartnerWebhookSecretRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/parameters': {
      id: '/_authenticated/admin/parameters'
      path: '/admin/parameters'
      fullPath: '/admin/parameters'
      preLoaderRoute: typeof AuthenticatedAdminParametersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/mobile-phase-reagents': {
      id: '/_authenticated/admin/mobile-phase-reagents'
      path: '/admin/mobile-phase-reagents'
      fullPath: '/admin/mobile-phase-reagents'
      preLoaderRoute: typeof AuthenticatedAdminMobilePhaseReagentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/method-groups': {
      id: '/_authenticated/admin/method-groups'
      path: '/admin/method-groups'
      fullPath: '/admin/method-groups'
      preLoaderRoute: typeof AuthenticatedAdminMethodGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/instruments': {
      id: '/_authenticated/admin/instruments'
      path: '/admin/instruments'
      fullPath: '/admin/instruments'
      preLoaderRoute: typeof AuthenticatedAdminInstrumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hplc-columns': {
      id: '/_authenticated/admin/hplc-columns'
      path: '/admin/hplc-columns'
      fullPath: '/admin/hplc-columns'
      preLoaderRoute: typeof AuthenticatedAdminHplcColumnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/compounds': {
      id: '/_authenticated/admin/compounds'
      path: '/admin/compounds'
      fullPath: '/admin/compounds'
      preLoaderRoute: typeof AuthenticatedAdminCompoundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/coc-fields': {
      id: '/_authenticated/admin/coc-fields'
      path: '/admin/coc-fields'
      fullPath: '/admin/coc-fields'
      preLoaderRoute: typeof AuthenticatedAdminCocFieldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access-logs': {
      id: '/_authenticated/admin/access-logs'
      path: '/admin/access-logs'
      fullPath: '/admin/access-logs'
      preLoaderRoute: typeof AuthenticatedAdminAccessLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/status/': {
      id: '/api/public/status/'
      path: '/api/public/status'
      fullPath: '/api/public/status/'
      preLoaderRoute: typeof ApiPublicStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lab-logs/timesheets/': {
      id: '/_authenticated/lab-logs/timesheets/'
      path: '/lab-logs/timesheets'
      fullPath: '/lab-logs/timesheets/'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/': {
      id: '/_authenticated/lab-logs/standard-preparations/'
      path: '/lab-logs/standard-preparations'
      fullPath: '/lab-logs/standard-preparations/'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/parameter-scouting/': {
      id: '/_authenticated/lab-logs/parameter-scouting/'
      path: '/lab-logs/parameter-scouting'
      fullPath: '/lab-logs/parameter-scouting/'
      preLoaderRoute: typeof AuthenticatedLabLogsParameterScoutingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/mobile-phase/': {
      id: '/_authenticated/lab-logs/mobile-phase/'
      path: '/lab-logs/mobile-phase'
      fullPath: '/lab-logs/mobile-phase/'
      preLoaderRoute: typeof AuthenticatedLabLogsMobilePhaseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/daily-backpressure/': {
      id: '/_authenticated/lab-logs/daily-backpressure/'
      path: '/lab-logs/daily-backpressure'
      fullPath: '/lab-logs/daily-backpressure/'
      preLoaderRoute: typeof AuthenticatedLabLogsDailyBackpressureIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/status/$batchId': {
      id: '/api/public/status/$batchId'
      path: '/api/public/status/$batchId'
      fullPath: '/api/public/status/$batchId'
      preLoaderRoute: typeof ApiPublicStatusBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders/intake': {
      id: '/api/public/orders/intake'
      path: '/api/public/orders/intake'
      fullPath: '/api/public/orders/intake'
      preLoaderRoute: typeof ApiPublicOrdersIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exports/$batchId': {
      id: '/api/public/exports/$batchId'
      path: '/api/public/exports/$batchId'
      fullPath: '/api/public/exports/$batchId'
      preLoaderRoute: typeof ApiPublicExportsBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/columns-data/$vendor': {
      id: '/api/public/columns-data/$vendor'
      path: '/api/public/columns-data/$vendor'
      fullPath: '/api/public/columns-data/$vendor'
      preLoaderRoute: typeof ApiPublicColumnsDataVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lab-logs/timesheets/reports': {
      id: '/_authenticated/lab-logs/timesheets/reports'
      path: '/lab-logs/timesheets/reports'
      fullPath: '/lab-logs/timesheets/reports'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/timesheets/history': {
      id: '/_authenticated/lab-logs/timesheets/history'
      path: '/lab-logs/timesheets/history'
      fullPath: '/lab-logs/timesheets/history'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/timesheets/daily': {
      id: '/_authenticated/lab-logs/timesheets/daily'
      path: '/lab-logs/timesheets/daily'
      fullPath: '/lab-logs/timesheets/daily'
      preLoaderRoute: typeof AuthenticatedLabLogsTimesheetsDailyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/new': {
      id: '/_authenticated/lab-logs/standard-preparations/new'
      path: '/lab-logs/standard-preparations/new'
      fullPath: '/lab-logs/standard-preparations/new'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/$id': {
      id: '/_authenticated/lab-logs/standard-preparations/$id'
      path: '/lab-logs/standard-preparations/$id'
      fullPath: '/lab-logs/standard-preparations/$id'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/mobile-phase/new': {
      id: '/_authenticated/lab-logs/mobile-phase/new'
      path: '/lab-logs/mobile-phase/new'
      fullPath: '/lab-logs/mobile-phase/new'
      preLoaderRoute: typeof AuthenticatedLabLogsMobilePhaseNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/mobile-phase/$id': {
      id: '/_authenticated/lab-logs/mobile-phase/$id'
      path: '/lab-logs/mobile-phase/$id'
      fullPath: '/lab-logs/mobile-phase/$id'
      preLoaderRoute: typeof AuthenticatedLabLogsMobilePhaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-logs/standard-preparations/batch/$groupId': {
      id: '/_authenticated/lab-logs/standard-preparations/batch/$groupId'
      path: '/lab-logs/standard-preparations/batch/$groupId'
      fullPath: '/lab-logs/standard-preparations/batch/$groupId'
      preLoaderRoute: typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChainOfCustodyRoute: typeof AuthenticatedChainOfCustodyRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVialLabelsRoute: typeof AuthenticatedVialLabelsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAccessLogsRoute: typeof AuthenticatedAdminAccessLogsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminCocFieldsRoute: typeof AuthenticatedAdminCocFieldsRoute
  AuthenticatedAdminCompoundsRoute: typeof AuthenticatedAdminCompoundsRoute
  AuthenticatedAdminHplcColumnsRoute: typeof AuthenticatedAdminHplcColumnsRoute
  AuthenticatedAdminInstrumentsRoute: typeof AuthenticatedAdminInstrumentsRoute
  AuthenticatedAdminMethodGroupsRoute: typeof AuthenticatedAdminMethodGroupsRoute
  AuthenticatedAdminMobilePhaseReagentsRoute: typeof AuthenticatedAdminMobilePhaseReagentsRoute
  AuthenticatedAdminParametersRoute: typeof AuthenticatedAdminParametersRoute
  AuthenticatedAdminPartnerWebhookSecretRoute: typeof AuthenticatedAdminPartnerWebhookSecretRoute
  AuthenticatedAdminQueueConfigRoute: typeof AuthenticatedAdminQueueConfigRoute
  AuthenticatedAdminRunListColumnsRoute: typeof AuthenticatedAdminRunListColumnsRoute
  AuthenticatedAdminTimesheetProjectsRoute: typeof AuthenticatedAdminTimesheetProjectsRoute
  AuthenticatedAdminTraysRoute: typeof AuthenticatedAdminTraysRoute
  AuthenticatedInstrumentCommOpenlabRoute: typeof AuthenticatedInstrumentCommOpenlabRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRoute
  AuthenticatedInventoryInstrumentsRoute: typeof AuthenticatedInventoryInstrumentsRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedMaintenanceHplcColumnsRoute: typeof AuthenticatedMaintenanceHplcColumnsRoute
  AuthenticatedMaintenanceKnowledgeBaseRoute: typeof AuthenticatedMaintenanceKnowledgeBaseRoute
  AuthenticatedMaintenancePartPickerRoute: typeof AuthenticatedMaintenancePartPickerRoute
  AuthenticatedMaintenanceTroubleshootingRoute: typeof AuthenticatedMaintenanceTroubleshootingRoute
  AuthenticatedMaterialReceiptsIdRoute: typeof AuthenticatedMaterialReceiptsIdRoute
  AuthenticatedMaterialReceiptsAccountingReportRoute: typeof AuthenticatedMaterialReceiptsAccountingReportRoute
  AuthenticatedMaterialReceiptsNewRoute: typeof AuthenticatedMaterialReceiptsNewRoute
  AuthenticatedRunListsIdRoute: typeof AuthenticatedRunListsIdRoute
  AuthenticatedRunListsGenerateRoute: typeof AuthenticatedRunListsGenerateRoute
  AuthenticatedSamplePrepAnalytesRoute: typeof AuthenticatedSamplePrepAnalytesRoute
  AuthenticatedSamplePrepEquipmentRoute: typeof AuthenticatedSamplePrepEquipmentRoute
  AuthenticatedSamplePrepMethodsRoute: typeof AuthenticatedSamplePrepMethodsRoute
  AuthenticatedSamplePrepQuickDilutionRoute: typeof AuthenticatedSamplePrepQuickDilutionRoute
  AuthenticatedSamplePrepSolventsRoute: typeof AuthenticatedSamplePrepSolventsRoute
  AuthenticatedSamplePrepVesselsRoute: typeof AuthenticatedSamplePrepVesselsRoute
  AuthenticatedSamplesBatchIdRoute: typeof AuthenticatedSamplesBatchIdRoute
  AuthenticatedSamplesNewRoute: typeof AuthenticatedSamplesNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedInstrumentCommIndexRoute: typeof AuthenticatedInstrumentCommIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedIssuesIndexRoute: typeof AuthenticatedIssuesIndexRoute
  AuthenticatedLabJournalIndexRoute: typeof AuthenticatedLabJournalIndexRoute
  AuthenticatedLabLogsIndexRoute: typeof AuthenticatedLabLogsIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedMaterialReceiptsIndexRoute: typeof AuthenticatedMaterialReceiptsIndexRoute
  AuthenticatedPendingOrdersIndexRoute: typeof AuthenticatedPendingOrdersIndexRoute
  AuthenticatedQueueIndexRoute: typeof AuthenticatedQueueIndexRoute
  AuthenticatedRunListsIndexRoute: typeof AuthenticatedRunListsIndexRoute
  AuthenticatedSamplePrepIndexRoute: typeof AuthenticatedSamplePrepIndexRoute
  AuthenticatedSamplesIndexRoute: typeof AuthenticatedSamplesIndexRoute
  AuthenticatedSchedulerIndexRoute: typeof AuthenticatedSchedulerIndexRoute
  AuthenticatedLabLogsMobilePhaseIdRoute: typeof AuthenticatedLabLogsMobilePhaseIdRoute
  AuthenticatedLabLogsMobilePhaseNewRoute: typeof AuthenticatedLabLogsMobilePhaseNewRoute
  AuthenticatedLabLogsStandardPreparationsIdRoute: typeof AuthenticatedLabLogsStandardPreparationsIdRoute
  AuthenticatedLabLogsStandardPreparationsNewRoute: typeof AuthenticatedLabLogsStandardPreparationsNewRoute
  AuthenticatedLabLogsTimesheetsDailyRoute: typeof AuthenticatedLabLogsTimesheetsDailyRoute
  AuthenticatedLabLogsTimesheetsHistoryRoute: typeof AuthenticatedLabLogsTimesheetsHistoryRoute
  AuthenticatedLabLogsTimesheetsReportsRoute: typeof AuthenticatedLabLogsTimesheetsReportsRoute
  AuthenticatedLabLogsDailyBackpressureIndexRoute: typeof AuthenticatedLabLogsDailyBackpressureIndexRoute
  AuthenticatedLabLogsMobilePhaseIndexRoute: typeof AuthenticatedLabLogsMobilePhaseIndexRoute
  AuthenticatedLabLogsParameterScoutingIndexRoute: typeof AuthenticatedLabLogsParameterScoutingIndexRoute
  AuthenticatedLabLogsStandardPreparationsIndexRoute: typeof AuthenticatedLabLogsStandardPreparationsIndexRoute
  AuthenticatedLabLogsTimesheetsIndexRoute: typeof AuthenticatedLabLogsTimesheetsIndexRoute
  AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute: typeof AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChainOfCustodyRoute: AuthenticatedChainOfCustodyRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVialLabelsRoute: AuthenticatedVialLabelsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAccessLogsRoute: AuthenticatedAdminAccessLogsRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminCocFieldsRoute: AuthenticatedAdminCocFieldsRoute,
  AuthenticatedAdminCompoundsRoute: AuthenticatedAdminCompoundsRoute,
  AuthenticatedAdminHplcColumnsRoute: AuthenticatedAdminHplcColumnsRoute,
  AuthenticatedAdminInstrumentsRoute: AuthenticatedAdminInstrumentsRoute,
  AuthenticatedAdminMethodGroupsRoute: AuthenticatedAdminMethodGroupsRoute,
  AuthenticatedAdminMobilePhaseReagentsRoute:
    AuthenticatedAdminMobilePhaseReagentsRoute,
  AuthenticatedAdminParametersRoute: AuthenticatedAdminParametersRoute,
  AuthenticatedAdminPartnerWebhookSecretRoute:
    AuthenticatedAdminPartnerWebhookSecretRoute,
  AuthenticatedAdminQueueConfigRoute: AuthenticatedAdminQueueConfigRoute,
  AuthenticatedAdminRunListColumnsRoute: AuthenticatedAdminRunListColumnsRoute,
  AuthenticatedAdminTimesheetProjectsRoute:
    AuthenticatedAdminTimesheetProjectsRoute,
  AuthenticatedAdminTraysRoute: AuthenticatedAdminTraysRoute,
  AuthenticatedInstrumentCommOpenlabRoute:
    AuthenticatedInstrumentCommOpenlabRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRoute,
  AuthenticatedInventoryInstrumentsRoute:
    AuthenticatedInventoryInstrumentsRoute,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedMaintenanceHplcColumnsRoute:
    AuthenticatedMaintenanceHplcColumnsRoute,
  AuthenticatedMaintenanceKnowledgeBaseRoute:
    AuthenticatedMaintenanceKnowledgeBaseRoute,
  AuthenticatedMaintenancePartPickerRoute:
    AuthenticatedMaintenancePartPickerRoute,
  AuthenticatedMaintenanceTroubleshootingRoute:
    AuthenticatedMaintenanceTroubleshootingRoute,
  AuthenticatedMaterialReceiptsIdRoute: AuthenticatedMaterialReceiptsIdRoute,
  AuthenticatedMaterialReceiptsAccountingReportRoute:
    AuthenticatedMaterialReceiptsAccountingReportRoute,
  AuthenticatedMaterialReceiptsNewRoute: AuthenticatedMaterialReceiptsNewRoute,
  AuthenticatedRunListsIdRoute: AuthenticatedRunListsIdRoute,
  AuthenticatedRunListsGenerateRoute: AuthenticatedRunListsGenerateRoute,
  AuthenticatedSamplePrepAnalytesRoute: AuthenticatedSamplePrepAnalytesRoute,
  AuthenticatedSamplePrepEquipmentRoute: AuthenticatedSamplePrepEquipmentRoute,
  AuthenticatedSamplePrepMethodsRoute: AuthenticatedSamplePrepMethodsRoute,
  AuthenticatedSamplePrepQuickDilutionRoute:
    AuthenticatedSamplePrepQuickDilutionRoute,
  AuthenticatedSamplePrepSolventsRoute: AuthenticatedSamplePrepSolventsRoute,
  AuthenticatedSamplePrepVesselsRoute: AuthenticatedSamplePrepVesselsRoute,
  AuthenticatedSamplesBatchIdRoute: AuthenticatedSamplesBatchIdRoute,
  AuthenticatedSamplesNewRoute: AuthenticatedSamplesNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedInstrumentCommIndexRoute: AuthenticatedInstrumentCommIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedIssuesIndexRoute: AuthenticatedIssuesIndexRoute,
  AuthenticatedLabJournalIndexRoute: AuthenticatedLabJournalIndexRoute,
  AuthenticatedLabLogsIndexRoute: AuthenticatedLabLogsIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedMaterialReceiptsIndexRoute:
    AuthenticatedMaterialReceiptsIndexRoute,
  AuthenticatedPendingOrdersIndexRoute: AuthenticatedPendingOrdersIndexRoute,
  AuthenticatedQueueIndexRoute: AuthenticatedQueueIndexRoute,
  AuthenticatedRunListsIndexRoute: AuthenticatedRunListsIndexRoute,
  AuthenticatedSamplePrepIndexRoute: AuthenticatedSamplePrepIndexRoute,
  AuthenticatedSamplesIndexRoute: AuthenticatedSamplesIndexRoute,
  AuthenticatedSchedulerIndexRoute: AuthenticatedSchedulerIndexRoute,
  AuthenticatedLabLogsMobilePhaseIdRoute:
    AuthenticatedLabLogsMobilePhaseIdRoute,
  AuthenticatedLabLogsMobilePhaseNewRoute:
    AuthenticatedLabLogsMobilePhaseNewRoute,
  AuthenticatedLabLogsStandardPreparationsIdRoute:
    AuthenticatedLabLogsStandardPreparationsIdRoute,
  AuthenticatedLabLogsStandardPreparationsNewRoute:
    AuthenticatedLabLogsStandardPreparationsNewRoute,
  AuthenticatedLabLogsTimesheetsDailyRoute:
    AuthenticatedLabLogsTimesheetsDailyRoute,
  AuthenticatedLabLogsTimesheetsHistoryRoute:
    AuthenticatedLabLogsTimesheetsHistoryRoute,
  AuthenticatedLabLogsTimesheetsReportsRoute:
    AuthenticatedLabLogsTimesheetsReportsRoute,
  AuthenticatedLabLogsDailyBackpressureIndexRoute:
    AuthenticatedLabLogsDailyBackpressureIndexRoute,
  AuthenticatedLabLogsMobilePhaseIndexRoute:
    AuthenticatedLabLogsMobilePhaseIndexRoute,
  AuthenticatedLabLogsParameterScoutingIndexRoute:
    AuthenticatedLabLogsParameterScoutingIndexRoute,
  AuthenticatedLabLogsStandardPreparationsIndexRoute:
    AuthenticatedLabLogsStandardPreparationsIndexRoute,
  AuthenticatedLabLogsTimesheetsIndexRoute:
    AuthenticatedLabLogsTimesheetsIndexRoute,
  AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute:
    AuthenticatedLabLogsStandardPreparationsBatchGroupIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatColumnAdvisorRoute: ApiChatColumnAdvisorRoute,
  ApiChatTroubleshootingRoute: ApiChatTroubleshootingRoute,
  ApiPublicColumnsDataVendorRoute: ApiPublicColumnsDataVendorRoute,
  ApiPublicExportsBatchIdRoute: ApiPublicExportsBatchIdRoute,
  ApiPublicOrdersIntakeRoute: ApiPublicOrdersIntakeRoute,
  ApiPublicStatusBatchIdRoute: ApiPublicStatusBatchIdRoute,
  ApiPublicStatusIndexRoute: ApiPublicStatusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
