CREATE TABLE public.library_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text,
  names text NOT NULL,
  cas_number text,
  molecular_weight text,
  molecular_size text,
  size_basis text,
  chemical_formula text,
  sequence text,
  salt_form text,
  termini_modifications text,
  notes text,
  confidence text,
  ambiguity_notes text,
  source_url text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.library_items TO authenticated;
GRANT ALL ON public.library_items TO service_role;

ALTER TABLE public.library_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "library_items select for authenticated"
  ON public.library_items FOR SELECT TO authenticated USING (true);

CREATE POLICY "library_items insert admin"
  ON public.library_items FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "library_items update admin"
  ON public.library_items FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "library_items delete admin"
  ON public.library_items FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE TRIGGER trg_library_items_updated_at
  BEFORE UPDATE ON public.library_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE UNIQUE INDEX library_items_cas_unique
  ON public.library_items (lower(cas_number)) WHERE cas_number IS NOT NULL;
CREATE UNIQUE INDEX library_items_names_unique
  ON public.library_items (lower(names)) WHERE names IS NOT NULL;

INSERT INTO public.library_items (category, names, cas_number, molecular_weight, molecular_size, size_basis, chemical_formula, sequence, salt_form, termini_modifications, notes, confidence, ambiguity_notes, source_url) VALUES
('Peptide','BPC-157; Bepecin','137525-51-0','1419.54 Da','15 aa','sequence length','C62H98N16O22','GEPPPGKPADDAGLV','neutral/free peptide','C-terminal free acid','Tissue-repair/gut-injury research peptide','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/compound/Bpc-157'),
('Peptide','BPC-157 acetate','1628202-19-6 / multiple vendor CAS values','1479.59 Da','15 aa + acetate','sequence length + counterion','C64H102N16O24','GEPPPGKPADDAGLV','acetate salt / associated acetate form','C-terminal free acid; acetate/counterion included in formula','Same peptide sold/reported as acetate salt','Medium - public records differ on acetate CAS','BPC-157 free peptide and acetate salt have different formulas/MW; verify vendor COA and salt factor.','https://pubchem.ncbi.nlm.nih.gov/compound/BPC-157-acetate'),
('Peptide','KPV','67727-97-3','342.43 Da','3 aa','sequence length','C16H30N4O4','KPV','neutral/free peptide','C-terminal free acid','Anti-inflammatory tripeptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','GHK','49557-75-7','340.38 Da','3 aa','sequence length','C14H24N6O4','GHK','neutral/free peptide','C-terminal free acid','Copper-binding tripeptide / wound-healing research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide complex','GHK-Cu; Copper tripeptide-1','49557-75-7 / complex records vary','403.93 Da approx.','3 aa + Cu','sequence length + metal complex','C14H22CuN6O4','GHK-Cu','metal complex; salt/hydration varies','Cu(II) complex of GHK','Cosmetic/wound-healing/copper peptide research','Medium - complex stoichiometry can vary','CAS/formula may refer to GHK or GHK-Cu complex depending on source.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','DSIP; Delta sleep-inducing peptide','62568-57-4','848.81 Da','9 aa','sequence length','C35H48N10O15','WAGGDASGE','neutral/free peptide','C-terminal free acid','Sleep/neuropeptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Selank','129954-34-3','751.87 Da','7 aa','sequence length','C33H57N11O9','TKPRPGP','neutral/free peptide','C-terminal free acid','Neuropeptide/anxiolytic research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Semax','80714-61-0','813.92 Da','7 aa','sequence length','C37H51N9O10S','MEHFPGP','neutral/free peptide','C-terminal free acid','Neuropeptide/cognitive research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Epitalon; Epithalon','307297-39-8','390.35 Da','4 aa','sequence length','C14H22N4O9','AEDG','neutral/free peptide','C-terminal free acid','Short-peptide bioregulator/telomere-aging research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Thymogen','63958-90-7','333.34 Da','2 aa','sequence length','C16H19N3O5','EW','neutral/free peptide','C-terminal free acid','Thymus/immune short-peptide bioregulator research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Vilon',NULL,'275.3 Da','2 aa','sequence length','C11H21N3O5','KE','neutral/free peptide','C-terminal free acid','Short-peptide bioregulator research','Medium - identity is clear, CAS not consistently indexed','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Pinealon',NULL,'418.4 Da','3 aa','sequence length','C15H26N6O8','EDR','neutral/free peptide','C-terminal free acid','Neuro/short-peptide bioregulator research','Medium - common sequence, CAS not consistently indexed','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Vesugen',NULL,'390.39 Da','3 aa','sequence length','C15H26N4O8','KED','neutral/free peptide','C-terminal free acid','Vascular short-peptide bioregulator research','Medium - common sequence, CAS not consistently indexed','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Crystagen',NULL,'319.27 Da','3 aa','sequence length','C11H17N3O8','EDG','neutral/free peptide','C-terminal free acid','Short-peptide bioregulator research','Medium - common sequence, CAS not consistently indexed','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Cardiogen',NULL,'489.48 Da','4 aa','sequence length','C18H31N7O9','AEDR','neutral/free peptide','C-terminal free acid','Cardiac short-peptide bioregulator research','Low/Medium - verify branded identity','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Bronchogen',NULL,'446.45 Da','4 aa','sequence length','C18H30N4O9','AEDL','neutral/free peptide','C-terminal free acid','Bronchial/lung short-peptide bioregulator research','Low/Medium - verify branded identity','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator','Livagen',NULL,'447.44 Da','4 aa','sequence length','C17H29N5O9','KEDG','neutral/free peptide','C-terminal free acid','Short-peptide bioregulator research','Low/Medium - verify branded identity','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Ac-SDKP','67368-29-0','487.5 Da','4 aa','sequence length','C20H33N5O9','SDKP','neutral/free peptide','N-acetyl; C-terminal free acid','Thymosin-beta-4 fragment / fibrosis research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','LL-37; Cathelicidin antimicrobial peptide fragment','154947-66-7','4493.26 Da','37 aa','sequence length','C205H340N60O53','LLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES','neutral/free peptide','C-terminal free acid','Antimicrobial peptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Thymosin alpha-1','62304-98-7','3108.28 Da','28 aa','sequence length','C129H215N33O55','SDAAVDTSSEITTKDLKEKKEVVEEAEN','neutral/free peptide','N-acetyl; C-terminal free acid','Immune-modulating peptide research/therapeutic','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','MOTS-c',NULL,'2174.59 Da','16 aa','sequence length','C101H152N28O22S2','MRWQEMGYIFYPRKLR','neutral/free peptide','C-terminal free acid','Mitochondrial-derived peptide/metabolic research','Medium - sequence commonly reported; CAS not consistently indexed','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Humanin','330936-69-1','2687.23 Da','24 aa','sequence length','C119H204N34O32S2','MAPRGFSCLLLLTSEIDLPVKRRA','neutral/free peptide','C-terminal free acid','Mitochondrial-derived peptide/neuroprotection research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','AOD-9604; hGH fragment 176-191','221231-10-3','1815.08 Da','16 aa','sequence length','C78H123N23O23S2','YLRIVQCRSVEGSCGF','neutral/free peptide','C-terminal free acid; 1 disulfide bond(s)','hGH-fragment/metabolic research','Medium - sequence/disulfide common; vendor termini can differ','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Angiotensin II','4474-91-3','1046.18 Da','8 aa','sequence length','C50H71N13O12','DRVYIHPF','neutral/free peptide','C-terminal free acid','Angiotensin receptor/endocrine research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Angiotensin 1-7','51833-78-4','899.0 Da','7 aa','sequence length','C41H62N12O11','DRVYIHP','neutral/free peptide','C-terminal free acid','Mas receptor/cardiovascular research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Angiotensin I','11128-99-7','1296.48 Da','10 aa','sequence length','C62H89N17O14','DRVYIHPFHL','neutral/free peptide','C-terminal free acid','Renin-angiotensin system peptide','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Bradykinin','58-82-2','1060.21 Da','9 aa','sequence length','C50H73N15O11','RPPGFSPFR','neutral/free peptide','C-terminal free acid','Inflammation/kinin receptor research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Substance P','33507-63-0','1347.63 Da','11 aa','sequence length','C63H98N18O13S','RPKPQQFFGLM','neutral/free peptide','C-terminal amide','Tachykinin/neuropeptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Kisspeptin-10; Metastin 45-54','374675-21-5','1302.44 Da','10 aa','sequence length','C63H83N17O14','YNWNSFGLRF','neutral/free peptide','C-terminal amide','Kisspeptin/GnRH axis research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','VIP; Vasoactive intestinal peptide','37221-79-7','3325.8 Da','28 aa','sequence length','C147H238N44O42S','HSDAVFTDNYTRLRKQMAVKKYLNSILN','neutral/free peptide','C-terminal amide','Vasoactive/neuropeptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','PACAP-38','137061-48-4','4534.26 Da','38 aa','sequence length','C203H331N63O53S','HSDGIFTDSYSRYRKQMAVKKYLAAVLGKRYKQRVKNK','neutral/free peptide','C-terminal amide','Pituitary adenylate cyclase-activating peptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Glucagon','16941-32-5','3482.75 Da','29 aa','sequence length','C153H225N43O49S','HSQGTFTSDYSKYLDSRRAQDFVQWLMNT','neutral/free peptide','C-terminal free acid','Glucose/endocrine peptide research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Oxytocin','50-56-6','1007.19 Da','9 aa','sequence length','C43H66N12O12S2','CYIQNCPLG','neutral/free peptide','C-terminal amide; 1 disulfide bond(s)','Neuropeptide/hormone research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/compound/oxytocin'),
('Peptide','Arginine vasopressin; Argipressin','11000-17-2','1084.23 Da','9 aa','sequence length','C46H65N15O12S2','CYFQNCPRG','neutral/free peptide','C-terminal amide; 1 disulfide bond(s)','Vasopressin receptor/endocrine research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Somatostatin-14','38916-34-6','1637.88 Da','14 aa','sequence length','C76H104N18O19S2','AGCKNFFWKTFTSC','neutral/free peptide','C-terminal free acid; 1 disulfide bond(s)','Somatostatin receptor/neuroendocrine research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Calcitonin salmon','47931-85-1','3431.85 Da','32 aa','sequence length','C145H240N44O48S2','CSNLSTCVLGKLSQELHKLQTYPRTNTGSGTP','neutral/free peptide','C-terminal amide; 1 disulfide bond(s)','Calcium metabolism/osteoporosis research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Calcitonin human','9007-12-9','3417.85 Da','32 aa','sequence length','C151H226N40O45S3','CGNLSTCMLGTYTQDFNKFHTFPQTAIGVGAP','neutral/free peptide','C-terminal amide; 1 disulfide bond(s)','Calcium metabolism research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Teriparatide; PTH 1-34','52232-67-4','4117.72 Da','34 aa','sequence length','C181H291N55O51S2','SVSEIQLMHNLGKHLNSMERVEWLRKKLQDVHNF','neutral/free peptide','C-terminal free acid','Parathyroid hormone fragment / bone metabolism research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide','Ziconotide; omega-conotoxin MVIIA','107452-89-1','2639.13 Da','25 aa','sequence length','C102H172N36O32S7','CKGKGAKCSRLMYDCCTGSCRSGKC','neutral/free peptide','C-terminal amide; 3 disulfide bond(s)','N-type calcium-channel peptide toxin/analgesic research','High - formula calculated from canonical sequence','Formula/MW exclude salts, counterions, hydrates, and vendor-specific acetate/TFA forms.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Semaglutide','910463-68-2','4113.58 Da','31 aa + C18 side chain','sequence length + lipidated modification','C187H291N45O59','Modified GLP-1 analog','free base / neutral peptide','Aib substitution; Lys26 linked through spacer to C18 fatty diacid; C-terminal amide','GLP-1 receptor agonist/metabolic research','High - PubChem formula/CAS confirmed','Formula excludes formulation salts/excipients; sequence contains noncanonical residues.','https://pubchem.ncbi.nlm.nih.gov/compound/Semaglutide'),
('Peptide therapeutic','Tirzepatide','2023788-19-2','4813 g/mol','39 aa + C20 side chain','sequence length + lipidated modification','C225H348N48O68','Modified GIP/GLP-1 analog','free base / neutral peptide','Aib substitutions; C20 fatty diacid via linker connected to Lys20','Dual GIP/GLP-1 receptor agonist/metabolic research','High - PubChem formula/CAS confirmed','Formula refers to parent compound; salts/excipients not included.','https://pubchem.ncbi.nlm.nih.gov/compound/156588324'),
('Peptide therapeutic','Liraglutide','204656-20-2','3751.20 Da','31 aa + C16 side chain','sequence length + lipidated modification','C172H265N43O51','Modified GLP-1 analog','free base / neutral peptide','Lys side-chain palmitoylation via glutamate spacer; Arg34 substitution','GLP-1 receptor agonist/metabolic research','High - PubChem formula/CAS confirmed','Formula excludes formulation salts/excipients.','https://pubchem.ncbi.nlm.nih.gov/compound/Liraglutide'),
('Peptide therapeutic','Exenatide; Exendin-4','141732-76-5','4186.57 Da','39 aa','sequence length','C184H282N50O60S','HGEGTFTSDLSKQMEEEAVRLFIEWLKNGGPSSGAPPPS','neutral/free peptide','C-terminal free acid','GLP-1 receptor agonist research/therapeutic','Medium - common sequence; verify formula against source','Free peptide formula; formulation salts excluded.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Lixisenatide','320367-13-3','4858.49 Da','44 aa','sequence length','C215H347N61O65S','Exendin-4 analog with C-terminal Lys6 extension','neutral/free peptide','C-terminal Lys6 extension; exact sequence should be source-verified','GLP-1 receptor agonist research/therapeutic','Medium - exact sequence/formula should be source checked','Free peptide formula; formulation salts excluded.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Pramlintide','196078-30-5','3949.39 Da','37 aa cyclic','sequence length','C171H267N51O53S2','KCNTATCATQRLANFLVHSSNNFGPILPPTNVGSNTY','neutral/free peptide','Amylin analog; disulfide bond; proline substitutions; amidation status source-dependent','Amylin analog/metabolic research','Medium - formula known but termini/salt should be checked','Verify amidated/free acid and acetate salt for vendor material.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Octreotide','83150-76-9','1019.24 Da','8 aa cyclic','sequence length','C49H66N10O10S2','D-Phe-Cys-Phe-D-Trp-Lys-Thr-Cys-Thr-ol','neutral/free peptide','D-amino acids; disulfide; C-terminal threoninol','Somatostatin analog research/therapeutic','High - common PubChem/manual formula','Acetate salt has different mass/formula.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Lanreotide','108736-35-2','1096.34 Da','8 aa cyclic','sequence length','C54H69N11O10S2','D-2-Nal-Cys-Tyr-D-Trp-Lys-Val-Cys-Thr-NH2','neutral/free peptide','D-amino acids; disulfide; C-terminal amide','Somatostatin analog research/therapeutic','Medium - verify salt/free base','Acetate salt/formulation not included.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Pasireotide','396091-73-9','1047.22 Da','6 aa cyclic','sequence length','C58H66N10O9','Cyclo[Hyp-Trp-Lys-Tyr(Bzl)-Phe-D-Trp]','neutral/free peptide','Cyclic hexapeptide; noncanonical residues','Somatostatin receptor analog research/therapeutic','Medium - modified cyclic peptide','Exact salt/formulation changes mass.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Desmopressin; dDAVP','16679-58-6','1069.22 Da','9 aa cyclic','sequence length','C46H64N14O12S2','1-deamino-8-D-Arg-vasopressin','neutral/free peptide','Deamino Cys1; D-Arg8; disulfide; C-terminal amide','V2 receptor/antidiuretic research','High/Medium - verify salt','Acetate salt has different MW.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Leuprolide; Leuprorelin','53714-56-0','1209.40 Da','9 aa + pyroGlu','sequence length + modified N-terminus','C59H84N16O12','pGlu-His-Trp-Ser-Tyr-D-Leu-Leu-Arg-Pro-NHEt','neutral/free peptide','pyroGlu; D-Leu; C-terminal ethylamide','GnRH agonist research/therapeutic','High/Medium - verify acetate salt','Acetate salt/formulations differ.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Goserelin','65807-02-5','1269.41 Da','10 aa modified','sequence length + modified residues','C59H84N18O14','pGlu-His-Trp-Ser-Tyr-D-Ser(tBu)-Leu-Arg-Pro-Azgly-NH2','neutral/free peptide','pyroGlu; D-Ser(tBu); azaglycine amide','GnRH agonist research/therapeutic','Medium - modified residues; verify source','Acetate salt/formulation not included.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Triptorelin','57773-63-4','1311.45 Da','10 aa modified','sequence length + modified residues','C64H82N18O13','pGlu-His-Trp-Ser-Tyr-D-Trp-Leu-Arg-Pro-Gly-NH2','neutral/free peptide','pyroGlu; D-Trp; C-terminal amide','GnRH agonist research/therapeutic','Medium - verify salt','Acetate/pamoate salts differ.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Cetrorelix','120287-85-6','1431.06 Da','10 aa modified','sequence length + modified residues','C70H92ClN17O14','D-Nal-D-Cpa-D-Pal-Ser-Tyr-D-Cit-Leu-Arg-Pro-D-Ala-NH2','neutral/free peptide','Multiple D/noncanonical residues; C-terminal amide','GnRH antagonist research/therapeutic','Medium - source verify','Salt/free base and stereochemistry matter.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Ganirelix','124904-93-4','1570.36 Da','10 aa modified','sequence length + modified residues','C80H113ClN18O13','D-Nal-D-Cpa-D-Pal-Ser-Tyr-D-hArg(Et2)-Leu-hArg(Et2)-Pro-D-Ala-NH2','neutral/free peptide','Multiple D/noncanonical residues; C-terminal amide','GnRH antagonist research/therapeutic','Medium - source verify','Salt/free base and stereochemistry matter.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Degarelix','214766-78-6','1632.30 Da','10 aa modified','sequence length + modified residues','C82H103ClN18O16','Modified GnRH antagonist decapeptide','neutral/free peptide','Multiple D/noncanonical residues','GnRH antagonist research/therapeutic','Medium - source verify','Formula/MW should be checked against exact acetate salt or free base.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Bremelanotide; PT-141','189691-06-3','1025.18 Da','7 aa cyclic','sequence length + cycle','C50H68N14O10','Ac-Nle-c[Asp-His-D-Phe-Arg-Trp-Lys]-OH','neutral/free peptide','N-acetyl; cyclic lactam; D-Phe; norleucine','Melanocortin receptor research/therapeutic','High/Medium - verify salt','Acetate salt has different formula/MW.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','Melanotan II','121062-08-6','1024.18 Da','7 aa cyclic','sequence length + cycle','C50H69N15O9','Ac-Nle-c[Asp-His-D-Phe-Arg-Trp-Lys]-NH2','neutral/free peptide','N-acetyl; cyclic lactam; D-Phe; norleucine; C-terminal amide','Melanocortin receptor research','High/Medium - verify acetate salt','Often sold as acetate; salt factor changes MW.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Afamelanotide; Melanotan I','75921-69-6','1646.85 Da','13 aa modified','sequence length','C78H111N21O19','Ac-Ser-Tyr-Ser-Nle-Glu-His-D-Phe-Arg-Trp-Gly-Lys-Pro-Val-NH2','neutral/free peptide','N-acetyl; D-Phe; norleucine; C-terminal amide','Melanocortin receptor / pigmentation research','Medium - verify sequence and formula','Salt/formulation not included.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Setmelanotide','920014-72-8','1117.31 Da','8 aa cyclic','sequence length + cycle','C49H68N18O9S2','Ac-Arg-c[Cys-D-Ala-His-D-Phe-Arg-Trp-Cys]-NH2','neutral/free peptide','Cyclic linkage and salt form must be confirmed','Melanocortin-4 receptor agonist research/therapeutic','Medium - source verify','Exact cyclic linkage and salt form must be confirmed.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','CJC-1295 without DAC; Mod GRF 1-29','863288-34-0','3367.97 Da','29 aa modified','sequence length','C152H252N44O42','YADAIFTQSYRKVLAQLSARKLLQDILSR-NH2','neutral/free peptide','GHRH analog substitutions; C-terminal amide','GHRH/GH secretagogue research','Medium - verify exact analog','Often confused with CJC-1295 DAC; salts vary.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','CJC-1295 with DAC','863288-34-0 / varies','~3647 Da plus DAC moiety','29 aa + DAC','sequence length + reactive linker','N/A - exact DAC conjugation varies','Modified GHRH(1-29) analog with DAC linker','DAC-modified peptide','Reactive maleimidopropionyl/DAC chemistry; albumin-binding derivative','GHRH/GH secretagogue research','Low/Medium - formulation ambiguous','Do not merge with no-DAC Mod GRF; exact formula depends on derivative.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','Sermorelin; GRF 1-29','86168-78-7','3357.93 Da','29 aa','sequence length','C149H246N44O42S','YADAIFTNSYRKVLGQLSARKLLQDIMSR-NH2','neutral/free peptide','C-terminal amide','GHRH analog research/therapeutic','Medium - verify salt','Acetate salt often used.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Tesamorelin','218949-48-5','5135.90 Da','44 aa + N-acyl modification','sequence length + modification','C221H366N72O67S','Trans-3-hexenoyl-GHRH(1-44)-NH2','neutral/free peptide','N-terminal trans-3-hexenoyl; C-terminal amide','GHRH analog/metabolic research/therapeutic','Medium - source verify','Acetate salt and formulations differ.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','Ipamorelin','170851-70-4','711.85 Da','5 aa modified','sequence length','C38H49N9O5','Aib-His-D-2-Nal-D-Phe-Lys-NH2','neutral/free peptide','Aib and D/noncanonical residues; C-terminal amide','Ghrelin/GH secretagogue research','Medium - source verify','Acetate salt usually reported separately.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','GHRP-6','87616-84-0','873.01 Da','6 aa modified','sequence length','C46H56N12O6','His-D-Trp-Ala-Trp-D-Phe-Lys-NH2','neutral/free peptide','D-amino acids; C-terminal amide','Ghrelin/GH secretagogue research','Medium - source verify','Acetate salt changes formula/MW.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','GHRP-2','158861-67-7','817.98 Da','6 aa modified','sequence length','C45H55N9O6','D-Ala-D-2-Nal-Ala-Trp-D-Phe-Lys-NH2','neutral/free peptide','D/noncanonical residues; C-terminal amide','Ghrelin/GH secretagogue research','Medium - source verify','Acetate salt changes formula/MW.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide research','Hexarelin','140703-51-1','887.05 Da','6 aa modified','sequence length','C47H58N12O6','His-D-2-Me-Trp-Ala-Trp-D-Phe-Lys-NH2','neutral/free peptide','D/noncanonical residues; C-terminal amide','Ghrelin/GH secretagogue research','Medium - source verify','Acetate salt changes formula/MW.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Icatibant','130308-48-4','1304.52 Da','10 aa modified','sequence length','C59H89N19O13S','D-Arg-Arg-Pro-Hyp-Gly-Thi-Ser-D-Tic-Oic-Arg','neutral/free peptide','Noncanonical residues; bradykinin B2 antagonist','Bradykinin receptor antagonist research/therapeutic','Medium - source verify','Acetate salt/formulation differs.','https://pubchem.ncbi.nlm.nih.gov/'),
('Peptide therapeutic','Bivalirudin','128270-60-0','2180.32 Da','20 aa modified','sequence length','C98H138N24O33','D-Phe-Pro-Arg-Pro-Gly-Gly-Gly-Gly-Asn-Gly-Asp-Phe-Glu-Glu-Ile-Pro-Glu-Glu-Tyr-Leu','neutral/free peptide','N-terminal D-Phe; peptide anticoagulant','Thrombin inhibitor / anticoagulant research','Medium - source verify','Trifluoroacetate/salt forms differ.','WhoStripebChem.URL'),
('Peptide therapeutic','Eptifibatide','188627-80-7','831.96 Da','7 aa cyclic','sequence length + cycle','C35H49N11O9S2','Cyclo[Mpa-Har-Gly-Asp-Trp-Pro-Cys]-NH2','neutral/free peptide','Disulfide/cyclic heptapeptide; homoarginine; mercaptopropionyl','GP IIb/IIIa antagonist research/therapeutic','Medium - source verify','Acetate salt and exact cyclic notation differ.','https://pubchem.ncbi.nlm.nih.gov/'),
('SARM','Ostarine; Enobosarm; MK-2866; GTx-024','841205-47-8','389.33 g/mol','small molecule','non-peptide small molecule','C19H14F3N3O3','N/A','neutral compound','Not an amino-acid peptide','Investigational nonsteroidal SARM / AR modulator research','High - PubChem formula indexed','Not a peptide; no amino acid composition.','https://pubchem.ncbi.nlm.nih.gov/compound/Enobosarm'),
('SARM','Ligandrol; LGD-4033; VK-5211','1165910-22-4','338.25 g/mol','small molecule','non-peptide small molecule','C14H12F6N2O','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','High - PubChem formula/CAS confirmed','Not a peptide; no amino acid composition.','https://pubchem.ncbi.nlm.nih.gov/compound/Ligandrol'),
('SARM','RAD-140; Testolone; Vosilasarm','1182367-47-0','393.8 g/mol','small molecule','non-peptide small molecule','C20H16ClN5O2','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','High - PubChem formula/CAS confirmed','Not a peptide; no amino acid composition.','https://pubchem.ncbi.nlm.nih.gov/compound/Ligandrol'),
('SARM','Andarine; S-4; GTX-007','401900-40-1','441.36 g/mol','small molecule','non-peptide small molecule','C19H18F3N3O6','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','High - PubChem formula/CAS confirmed','Not a peptide; no amino acid composition.','https://pubchem.ncbi.nlm.nih.gov/compound/andarine'),
('SARM','S-23','1010396-29-8','416.8 g/mol','small molecule','non-peptide small molecule','C18H13ClF4N2O3','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','High - PubChem formula/CAS confirmed','Not a peptide; no amino acid composition.','https://pubchem.ncbi.nlm.nih.gov/compound/S-23'),
('SARM-like','YK-11','1370003-76-1','430.53 g/mol','small molecule steroidal','non-peptide small molecule','C25H34O6','N/A','neutral compound','Not an amino-acid peptide','Steroidal AR partial agonist / myostatin-related research','Medium - vendor/database formulas agree; not PubChem-confirmed in this pass','Often grouped with SARMs but structurally steroidal/SARM-like.','https://www.caymanchem.com/product/9003137/yk-11'),
('SARM','ACP-105','899821-23-9','285.34 g/mol','small molecule','non-peptide small molecule','C16H19N3O2','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','Medium - source verify','Not a peptide; formula should be checked against PubChem/Cayman before procurement.','https://pubchem.ncbi.nlm.nih.gov/'),
('SARM','AC-262536','870888-46-3','278.35 g/mol','small molecule','non-peptide small molecule','C18H18N2O','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','Medium - source verify','Not a peptide; formula should be checked against source.','https://pubchem.ncbi.nlm.nih.gov/'),
('SARM','LGD-3303','917891-35-1','344.33 g/mol','small molecule','non-peptide small molecule','C16H14F3N3O2','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','Medium - source verify','Not a peptide; formula should be checked against source.','https://pubchem.ncbi.nlm.nih.gov/'),
('SARM','BMS-564929','627530-84-1','494.36 g/mol','small molecule','non-peptide small molecule','C18H16F6N2O5S','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','Medium - source verify','Not a peptide; formula should be checked against source.','https://pubchem.ncbi.nlm.nih.gov/'),
('SARM','MK-0773','606143-89-9','515.54 g/mol','small molecule','non-peptide small molecule','C26H25F3N4O4','N/A','neutral compound','Not an amino-acid peptide','Investigational SARM / AR modulator research','Medium - source verify','Not a peptide; formula should be checked against source.','https://pubchem.ncbi.nlm.nih.gov/'),
('Related non-peptide','Ibutamoren; MK-677','159752-10-0','528.66 g/mol','small molecule','non-peptide small molecule','C27H36N4O5S','N/A','neutral compound','Not an amino-acid peptide','Ghrelin receptor agonist / GH secretagogue research; not a peptide and not a SARM','Medium - source verify','Included because commonly grouped with peptide/SARM research products but pharmacologically distinct.','https://pubchem.ncbi.nlm.nih.gov/'),
('Related non-peptide','GW-501516; Cardarine','317318-70-0','453.50 g/mol','small molecule','non-peptide small molecule','C21H18F3NO3S2','N/A','neutral compound','Not an amino-acid peptide','PPAR-delta agonist research; not a peptide and not a SARM','Medium - source verify','Included because commonly grouped with SARM/research-chemical lists but pharmacologically distinct.','https://pubchem.ncbi.nlm.nih.gov/'),
('Related non-peptide','SR9009; Stenabolic','1379686-30-2','437.94 g/mol','small molecule','non-peptide small molecule','C20H24ClN3O4S','N/A','neutral compound','Not an amino-acid peptide','REV-ERB agonist research; not a peptide and not a SARM','Medium - source verify','Included because commonly grouped with SARM/research-chemical lists but pharmacologically distinct.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator mixture','Thymalin',NULL,'mixture','peptide mixture','mixture/extract','mixture','Mixture','peptide extract/mixture','No single formula','Thymus-derived peptide bioregulator research','Ambiguous - not a single compound','No single CAS/formula/MW/sequence; treat as product/extract, not a pure compound.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator mixture','Cortexin',NULL,'mixture','peptide mixture','mixture/extract','mixture','Mixture','peptide extract/mixture','No single formula','Neuropeptide extract/bioregulator research','Ambiguous - not a single compound','No single CAS/formula/MW/sequence; treat as product/extract, not a pure compound.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator mixture','Prostatilen',NULL,'mixture','peptide mixture','mixture/extract','mixture','Mixture','peptide extract/mixture','No single formula','Prostate-derived peptide extract research','Ambiguous - not a single compound','No single CAS/formula/MW/sequence; treat as product/extract, not a pure compound.','https://pubchem.ncbi.nlm.nih.gov/'),
('Bioregulator mixture','Cortagen',NULL,NULL,NULL,'sequence length',NULL,'AEDP','neutral/free peptide','C-terminal free acid','Short-peptide bioregulator research','Low - branded mixture/peptide identity varies','Some databases report it as a single peptide AEDP; vendors often sell mixtures.','https://pubchem.ncbi.nlm.nih.gov/');